// Minimal HR vertical taxonomy for semantic domain extraction.
// Scope: semantic layer only. No analyzer/evidence/simulation coupling here.

export const HR_VERTICAL_DOMAINS = [
  {
    domain: "talent_acquisition",
    strongPhrases: [
      "talent acquisition",
      "full-cycle recruiting",
      "full cycle recruiting",
      "pipeline recruiting",
      "candidate sourcing",
      "requisition",
      "ats",
      "talent operations",
      "채용 운영",
      "채용",
      "리크루터",
      "채용 전형",
      "채용 파이프라인",
      "인터뷰 운영",
    ],
    conceptBundles: [
      ["candidate", "sourcing"],
      ["interview", "coordination"],
      ["채용", "운영"],
      ["채용", "프로세스"],
      ["채용", "전형"],
    ],
  },
  {
    domain: "hr_operations",
    strongPhrases: [
      "people ops",
      "people operations",
      "talent operations",
      "hr operations",
      "hr operation",
      "인사운영",
      "인사 행정",
      "인사행정",
      "입퇴사",
      "근태",
      "payroll",
      "4대보험",
      "hris",
      "온보딩",
    ],
    conceptBundles: [
      ["인사", "운영"],
      ["입퇴사", "관리"],
      ["근태", "관리"],
      ["4대보험", "신고"],
      ["hris", "운영"],
    ],
  },
  {
    domain: "compensation_performance",
    strongPhrases: [
      "compensation",
      "benefits",
      "total rewards",
      "salary review",
      "성과관리",
      "성과관리",
      "성과 관리",
      "평가",
      "평가보상",
      "보상",
      "복리후생",
      "calibration",
    ],
    conceptBundles: [
      ["성과", "관리"],
      ["salary", "review"],
      ["평가", "운영"],
      ["보상", "체계"],
      ["복리후생", "운영"],
    ],
  },
  {
    domain: "hrbp_er",
    strongPhrases: [
      "hrbp",
      "hr business partner",
      "hr business partnering",
      "people partner",
      "employee relations",
      "직원 관계",
      "조직 구조",
      "조직 설계",
      "인력 운영 전략",
      "er",
      "headcount planning",
      "grievance",
      "조직개편",
      "인력운영",
      "인력 운영",
      "조직설계",
      "구성원 이슈",
    ],
    conceptBundles: [
      ["employee", "relations"],
      ["headcount", "planning"],
      ["조직", "개편"],
      ["인력", "운영"],
      ["직원", "고충"],
    ],
  },
  {
    domain: "learning_development",
    strongPhrases: [
      "l&d",
      "learning and development",
      "learning development",
      "people development",
      "교육",
      "직무 교육",
      "사내 교육",
      "러닝",
      "curriculum",
      "onboarding program",
    ],
    conceptBundles: [
      ["교육", "운영"],
      ["교육", "프로그램"],
      ["learning", "development"],
      ["온보딩", "프로그램"],
    ],
  },
];
