export const ACTION_TEMPLATES = {
  REWRITE_JD_LINK: {
    id: "rewrite_jd_link",
    signalKeys: [
      "TASK__CORE_COVERAGE_LOW",
      "TASK__EVIDENCE_TOO_WEAK",
      "ROLE_SKILL__LOW_SEMANTIC_SIMILARITY",
    ],
    category: "jd_link",
    title: "JD 핵심 업무 문장 추가",
    task: "JD 요구, 실제 수행 행동, 결과 순서로 1문장을 다시 작성",
    example: "시장 데이터 분석, 구매 전략 수립, 원가 8% 절감",
    impact: "high",
    ease: "high",
    dedupeGroup: "jd_link",
    actionFamily: "rewrite",
    primaryCluster: "jd_alignment",
  },
  ATTACH_JD_KEYWORD_TO_ACTION: {
    id: "attach_jd_keyword_to_action",
    signalKeys: ["ROLE_SKILL__JD_KEYWORD_ABSENCE", "DOMAIN__WEAK__KEYWORD_SPARSE"],
    category: "jd_link",
    title: "JD 키워드를 행동산출물과 함께 연결",
    task: "JD 키워드를 단독으로 넣지 말고 행동산출물과 한 문장으로 묶기",
    example: "SAP 사용 경험, 발주 데이터 정리 및 월간 리포트 작성",
    impact: "high",
    ease: "high",
    dedupeGroup: "jd_link",
    actionFamily: "rewrite",
    primaryCluster: "jd_alignment",
  },
  PRIORITIZE_MUST_REQUIREMENT: {
    id: "prioritize_must_requirement",
    signalKeys: ["ROLE_SKILL__MUST_HAVE_MISSING", "GATE__CRITICAL_EXPERIENCE_GAP"],
    category: "requirement_match",
    title: "필수 요구와 직접 맞닿는 문장 먼저 보강",
    task: "JD 필수 요구 1개당 대응 경험 1개를 먼저 배치",
    example: "필수 역량 3개를 먼저 추려 각 항목에 대응 문장 배치",
    impact: "high",
    ease: "medium",
    dedupeGroup: "must_match",
    actionFamily: "requirement_match",
    primaryCluster: "hard_gate",
  },
  REORDER_RESUME_FOR_JD_PRIORITY: {
    id: "reorder_resume_for_jd_priority",
    signalKeys: ["TASK__CORE_COVERAGE_LOW", "ROLE_SKILL__LOW_SEMANTIC_SIMILARITY"],
    category: "ordering",
    title: "JD 핵심 과업 순서대로 이력서 재배치",
    task: "JD 상위 과업과 가장 가까운 경험을 상단 항목으로 올리기",
    example: "지원 직무와 가장 가까운 프로젝트를 첫 항목에 배치",
    impact: "high",
    ease: "medium",
    dedupeGroup: "ordering",
    actionFamily: "structure",
    primaryCluster: "jd_alignment",
  },
  SPLIT_OVERLOADED_SENTENCE: {
    id: "split_overloaded_sentence",
    signalKeys: ["LOW_CONTENT_DENSITY_RISK", "PROOF_WEAK"],
    category: "clarity",
    title: "한 문장에 핵심 1개만 남기기",
    task: "역할행동성과가 섞인 문장은 핵심 기준으로 분리",
    example: "기획/운영/성과를 한 줄에 몰지 말고 2~3개 항목으로 분리",
    impact: "medium",
    ease: "high",
    dedupeGroup: "clarity",
    actionFamily: "structure",
    primaryCluster: "evidence_strength",
  },
  WRITE_TRANSITION_BRIDGE: {
    id: "write_transition_bridge",
    signalKeys: [
      "SIMPLE__ROLE_SHIFT",
      "SIMPLE__DOMAIN_SHIFT",
      "ROLE_DOMAIN_SHIFT",
      "TITLE_DOMAIN_SHIFT",
    ],
    category: "transition",
    title: "이전 경험과 새 JD를 직접 연결",
    task: "이전 경험의 핵심 역량 1개를 새 JD 핵심 과업 1개와 직접 연결",
    example: "분석 경험을 기반으로 전략 의사결정 지원 성과로 연결",
    impact: "high",
    ease: "medium",
    dedupeGroup: "transition_bridge",
    actionFamily: "bridge",
    primaryCluster: "transition_logic",
  },
  TRANSLATE_EXPERIENCE_TO_BUSINESS_VALUE: {
    id: "translate_experience_to_business_value",
    signalKeys: ["RISK__EXECUTION_IMPACT_GAP", "IMPACT_WEAK"],
    category: "transition",
    title: "익숙한 일 설명 대신 회사 가치로 번역",
    task: "내가 하던 일이 아니라 회사의 돈시간성과에 준 효과로 설명",
    example: "운영 경험, 리드타임 단축 / 비용 절감 / 품질 안정화",
    impact: "high",
    ease: "medium",
    dedupeGroup: "transition_bridge",
    actionFamily: "bridge",
    primaryCluster: "evidence_strength",
  },
  NARROW_DOMAIN_GAP: {
    id: "narrow_domain_gap",
    signalKeys: ["DOMAIN__MISMATCH__JOB_FAMILY", "GATE__DOMAIN_MISMATCH__JOB_FAMILY"],
    category: "transition",
    title: "도메인 차이를 줄이는 유사 경험 먼저 제시",
    task: "다른 점보다 비슷한 업무 구조와 공통 역량을 먼저 배치",
    example: "산업은 달라도 분석운영조율 구조가 같은 경험 먼저 제시",
    impact: "high",
    ease: "medium",
    dedupeGroup: "domain_bridge",
    actionFamily: "bridge",
    primaryCluster: "domain_fit",
  },
  JUSTIFY_TRANSITION_WITH_PERFORMANCE_LOGIC: {
    id: "justify_transition_with_performance_logic",
    signalKeys: ["SIMPLE__ROLE_SHIFT", "ROLE_DOMAIN_SHIFT"],
    category: "transition",
    title: "전환 이유보다 성과 가능성 중심으로 정리",
    task: "왜 하고 싶은지가 아니라 왜 잘할 수 있는지 근거 중심으로 작성",
    example: "유사 문제 해결 경험이 있어 빠르게 성과 가능",
    impact: "medium",
    ease: "medium",
    dedupeGroup: "transition_bridge",
    actionFamily: "bridge",
    primaryCluster: "transition_logic",
  },
  PREEMPT_TRANSITION_OBJECTION: {
    id: "preempt_transition_objection",
    signalKeys: [
      "DOMAIN__MISMATCH__JOB_FAMILY",
      "TITLE_DOMAIN_SHIFT",
      "RISK__ROLE_LEVEL_MISMATCH",
    ],
    category: "transition",
    title: "전환 리스크를 먼저 해소하는 문장 추가",
    task: "가장 큰 전환 의심 포인트 1개를 골라 해소 문장 1줄 추가",
    example: "도메인 차이는 있지만 동일한 운영 구조 경험으로 빠르게 적응 가능",
    impact: "high",
    ease: "medium",
    dedupeGroup: "transition_objection",
    actionFamily: "bridge",
    primaryCluster: "transition_logic",
  },
  ADD_QUANT_RESULT: {
    id: "add_quant_result",
    signalKeys: ["EVIDENCE_THIN", "IMPACT_WEAK", "PROOF_WEAK"],
    category: "evidence",
    title: "성과를 숫자로 바꾸기",
    task: "시간비용매출품질처리량 중 하나로 결과를 수치화",
    example: "처리시간 30% 단축 / 오류율 감소 / 원가 절감",
    impact: "high",
    ease: "medium",
    dedupeGroup: "quant",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  ADD_DELIVERABLE_EVIDENCE: {
    id: "add_deliverable_evidence",
    signalKeys: ["EVIDENCE_THIN", "TASK__EVIDENCE_TOO_WEAK"],
    category: "evidence",
    title: "성과 수치가 없으면 산출물이라도 남기기",
    task: "보고서대시보드프로세스문서 등 결과물을 문장에 명시",
    example: "월간 리포트 작성 / 운영 가이드 정리 / 분석 대시보드 구축",
    impact: "medium",
    ease: "high",
    dedupeGroup: "evidence",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  SEPARATE_PERSONAL_CONTRIBUTION: {
    id: "separate_personal_contribution",
    signalKeys: ["PROOF_WEAK", "RISK__EXECUTION_IMPACT_GAP"],
    category: "evidence",
    title: "팀 성과 속 내 기여를 분리",
    task: "팀 결과와 별도로 내가 맡은 역할판단실행을 따로 쓰기",
    example: "전체 성과 중 내가 설계조율분석한 부분을 명시",
    impact: "high",
    ease: "medium",
    dedupeGroup: "ownership",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  ADD_BEFORE_AFTER_COMPARISON: {
    id: "add_before_after_comparison",
    signalKeys: ["IMPACT_WEAK", "PROOF_WEAK"],
    category: "evidence",
    title: "개선 성과는 전후 비교로 표현",
    task: "개선 전 상태와 개선 후 변화를 한 쌍으로 작성",
    example: "수작업 2시간, 자동화 후 20분",
    impact: "high",
    ease: "high",
    dedupeGroup: "quant",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  TRANSLATE_ROUTINE_WORK_INTO_IMPACT: {
    id: "translate_routine_work_into_impact",
    signalKeys: ["LOW_CONTENT_DENSITY_RISK", "EVIDENCE_THIN"],
    category: "evidence",
    title: "반복업무도 성과 언어로 번역",
    task: "단순 수행이 아니라 운영 안정성속도정확성 효과를 붙이기",
    example: "정기 운영, 오류 감소 / 납기 안정화 / 대응 속도 개선",
    impact: "medium",
    ease: "medium",
    dedupeGroup: "impact_translation",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  ATTACH_TOOL_WITH_CONTEXT: {
    id: "attach_tool_with_context",
    signalKeys: ["ROLE_SKILL__JD_KEYWORD_ABSENCE", "TASK__EVIDENCE_TOO_WEAK"],
    category: "tool_evidence",
    title: "도구 이름보다 활용 맥락 추가",
    task: "도구 이름 옆에 어떤 작업에 어떻게 썼는지 함께 쓰기",
    example: "Excel로 수요 데이터 정리 및 월간 추이 분석",
    impact: "high",
    ease: "high",
    dedupeGroup: "tool_evidence",
    actionFamily: "evidence",
    primaryCluster: "jd_alignment",
  },
  ADD_SKILL_EVIDENCE_BULLET: {
    id: "add_skill_evidence_bullet",
    signalKeys: ["PROOF_WEAK", "ROLE_SKILL__LOW_SEMANTIC_SIMILARITY"],
    category: "tool_evidence",
    title: "주장한 핵심 스킬에 근거 사례 추가",
    task: "핵심 스킬 1개마다 실제 사례 1개를 붙이기",
    example: "문제해결/협업/분석력 각각 사례 1개씩 추가",
    impact: "high",
    ease: "medium",
    dedupeGroup: "skill_evidence",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
  BRIDGE_MISSING_REQUIREMENT_WITH_ADJACENT_EVIDENCE: {
    id: "bridge_missing_requirement_with_adjacent_evidence",
    signalKeys: ["ROLE_SKILL__MUST_HAVE_MISSING", "GATE__CRITICAL_EXPERIENCE_GAP"],
    category: "requirement_bridge",
    title: "부족한 필수요건은 유사 경험으로 보완",
    task: "없는 자격경험 대신 가장 가까운 실무 경험을 전면 배치",
    example: "자격 없음, 해당 영역 운영/분석/개선 경험으로 보강",
    impact: "high",
    ease: "medium",
    dedupeGroup: "requirement_bridge",
    actionFamily: "gate_response",
    primaryCluster: "hard_gate",
  },
  OFFSET_YEAR_GAP_WITH_DEPTH: {
    id: "offset_year_gap_with_depth",
    signalKeys: ["SENIORITY__UNDER_MIN_YEARS", "TITLE_SENIORITY_MISMATCH"],
    category: "requirement_bridge",
    title: "연차 부족은 경험 깊이로 완충",
    task: "기간보다 맡은 범위책임성과 강도를 더 선명하게 쓰기",
    example: "짧은 기간 내 핵심 과업 반복 수행과 직접 책임 강조",
    impact: "high",
    ease: "medium",
    dedupeGroup: "year_gap",
    actionFamily: "seniority_positioning",
    primaryCluster: "seniority_gap",
  },
  GATE_REQUIREMENT_RESPONSE: {
    id: "gate_requirement_response",
    signalKeys: ["GATE__SENIOR_LEVEL_REQUIRED", "GATE__AGE", "GATE__REQUIRED_CERT"],
    category: "gate_response",
    title: "Directly address requirement gaps",
    task: "Match your closest equivalent experience to the explicit requirement to reduce perceived gate mismatch.",
    example:
      "If the JD asks for '5+ years PM ownership', show cases where you owned roadmap decisions even without the exact title.",
    impact: 0.82,
    ease: 0.65,
    dedupeGroup: "gate_response",
    actionFamily: "gate",
    primaryCluster: "hard_gate",
  },
  GATE_SCOPE_REINTERPRETATION: {
    id: "gate_scope_reinterpretation",
    signalKeys: ["GATE__SENIOR_LEVEL_REQUIRED", "SENIORITY__UNDER_MIN_YEARS"],
    category: "gate_response",
    title: "Reframe scope to reduce gate friction",
    task: "Position your past work in terms of scope and decision ownership to align with the senior role expectation.",
    example:
      "Highlight where you led features or decisions even if you did not hold a formal senior title.",
    impact: 0.78,
    ease: 0.70,
    dedupeGroup: "gate_positioning",
    actionFamily: "gate",
    primaryCluster: "hard_gate",
  },
  BRIDGE_MISSING_TOOL_WITH_WORKFLOW_SIMILARITY: {
    id: "bridge_missing_tool_with_workflow_similarity",
    signalKeys: ["ROLE_SKILL__MUST_HAVE_MISSING", "ROLE_SKILL__JD_KEYWORD_ABSENCE"],
    category: "tool_evidence",
    title: "없는 툴은 유사 workflow 경험으로 보완",
    task: "동일 목적의 유사 도구작업 흐름을 연결해 적응 가능성 제시",
    example: "다른 BI/ERP 도구 경험을 목적 기준으로 연결",
    impact: "medium",
    ease: "medium",
    dedupeGroup: "tool_bridge",
    actionFamily: "bridge",
    primaryCluster: "jd_alignment",
  },
  PROMOTE_RECENT_RELEVANT_EXPERIENCE: {
    id: "promote_recent_relevant_experience",
    signalKeys: ["RISK__TIMELINE_MISMATCH", "TITLE_DOMAIN_SHIFT"],
    category: "ordering",
    title: "최근의 관련 경험을 먼저 배치",
    task: "최근 경험 중 지원 직무와 가까운 항목을 상단으로 올리기",
    example: "오래된 대표 경험보다 최근의 직접 관련 경험을 먼저 제시",
    impact: "medium",
    ease: "high",
    dedupeGroup: "ordering",
    actionFamily: "structure",
    primaryCluster: "timeline_risk",
  },
  REPLACE_VAGUE_EXPRESSION: {
    id: "replace_vague_expression",
    signalKeys: ["LOW_CONTENT_DENSITY_RISK", "PROOF_WEAK"],
    category: "clarity",
    title: "모호한 표현을 구체 행동으로 교체",
    task: "다양한/전반적/성공적 같은 표현을 실제 행동으로 바꾸기",
    example: "전반적 관리, 주간 발주 일정 조정 및 재고 이슈 대응",
    impact: "medium",
    ease: "high",
    dedupeGroup: "clarity",
    actionFamily: "structure",
    primaryCluster: "evidence_strength",
  },
  CLARIFY_SCOPE_AND_LEVEL: {
    id: "clarify_scope_and_level",
    signalKeys: ["RISK__ROLE_LEVEL_MISMATCH", "TITLE_SENIORITY_MISMATCH"],
    category: "ownership",
    title: "책임 범위와 레벨을 분명히 쓰기",
    task: "직접 수행 / 지원 / 주도 여부를 구분해서 표현",
    example: "지원과 주도를 섞지 말고 책임 범위를 분리",
    impact: "high",
    ease: "medium",
    dedupeGroup: "ownership",
    actionFamily: "structure",
    primaryCluster: "transition_logic",
  },
  INSERT_OBJECTION_HANDLING_LINE: {
    id: "insert_objection_handling_line",
    signalKeys: [
      "GATE__AGE",
      "GATE__SALARY_MISMATCH",
      "GATE__CRITICAL_EXPERIENCE_GAP",
      "GATE__DOMAIN_MISMATCH__JOB_FAMILY",
    ],
    category: "objection",
    title: "가장 큰 조건 리스크를 먼저 방어",
    task: "상단 1문장으로 가장 큰 조건 리스크에 대한 방어 논리를 추가",
    example: "조건 차이가 있지만 즉시 기여 가능한 직접 경험을 먼저 강조",
    impact: "high",
    ease: "medium",
    dedupeGroup: "objection",
    actionFamily: "gate_response",
    primaryCluster: "hard_gate",
  },
  MERGE_DUPLICATE_BULLETS_AND_STRENGTHEN_ONE: {
    id: "merge_duplicate_bullets_and_strengthen_one",
    signalKeys: ["LOW_CONTENT_DENSITY_RISK", "EVIDENCE_THIN"],
    category: "clarity",
    title: "비슷한 항목은 줄이고 대표 사례를 강화",
    task: "유사 항목 2개를 합치고 더 강한 사례 1개를 남기기",
    example: "비슷한 운영 경험 여러 줄보다 대표 사례 1개를 선명하게 정리",
    impact: "medium",
    ease: "high",
    dedupeGroup: "clarity",
    actionFamily: "structure",
    primaryCluster: "evidence_strength",
  },
  SENIORITY_POSITIONING: {
    id: "seniority_positioning",
    signalKeys: ["SENIORITY__UNDER_MIN_YEARS", "TITLE_SENIORITY_MISMATCH"],
    category: "seniority_positioning",
    title: "연차보다 맡은 수준과 반복 경험을 앞세우기",
    task: "기간이 짧아도 직접 맡은 범위와 반복 수행한 핵심 업무를 먼저 드러내기",
    example: "짧은 기간이지만 월간 운영 리듬을 직접 맡아 반복 수행",
    impact: "high",
    ease: "medium",
    dedupeGroup: "seniority_positioning",
    actionFamily: "seniority_positioning",
    primaryCluster: "seniority_gap",
  },
  SCOPE_RESET_TARGET: {
    id: "scope_reset_target",
    signalKeys: ["RISK__ROLE_LEVEL_MISMATCH", "TITLE_SENIORITY_MISMATCH"],
    category: "scope_reset",
    title: "지원 레벨에 맞는 책임 범위로 표현 정렬",
    task: "과도하게 넓거나 높은 표현 대신 실제 책임 범위를 지원 레벨에 맞춰 조정",
    example: "총괄 대신 담당 범위와 의사결정 구간을 구체적으로 명시",
    impact: "medium",
    ease: "medium",
    dedupeGroup: "scope_reset",
    actionFamily: "structure",
    primaryCluster: "transition_logic",
  },
  SALARY_RANGE_RESET: {
    id: "salary_range_reset",
    signalKeys: ["GATE__SALARY_MISMATCH"],
    category: "salary_reset",
    title: "보상 기대치보다 즉시 기여 가능성을 먼저 정렬",
    task: "상단 문장과 경력 요약에서 보상보다 즉시 투입 가능한 역할을 먼저 강조",
    example: "보상 조건 언급보다 운영 안정화와 성과 기여 경험을 먼저 배치",
    impact: "high",
    ease: "medium",
    dedupeGroup: "salary_reset",
    actionFamily: "gate_response",
    primaryCluster: "hard_gate",
  },
  CRITICAL_GAP_SUBSTITUTE: {
    id: "critical_gap_substitute",
    signalKeys: ["GATE__CRITICAL_EXPERIENCE_GAP", "ROLE_SKILL__MUST_HAVE_MISSING"],
    category: "critical_gap",
    title: "핵심 공백은 가장 가까운 대체 경험으로 메우기",
    task: "없는 필수 경험을 직접 메우려 하지 말고 가장 인접한 실무 경험을 상단에 재배치",
    example: "정확히 같은 도메인은 아니어도 동일한 운영 구조와 성과 경험을 먼저 제시",
    impact: "high",
    ease: "medium",
    dedupeGroup: "critical_gap",
    actionFamily: "gate_response",
    primaryCluster: "hard_gate",
  },
  DOMAIN_REFRAME_COMMON_KPI: {
    id: "domain_reframe_common_kpi",
    signalKeys: ["DOMAIN__MISMATCH__JOB_FAMILY", "ROLE_DOMAIN_SHIFT", "DOMAIN__WEAK__KEYWORD_SPARSE"],
    category: "domain_reframe",
    title: "도메인 차이보다 공통 KPI와 운영 구조를 먼저 연결",
    task: "산업이 달라도 공통으로 관리한 지표, 프로세스, 성과 구조를 먼저 드러내기",
    example: "업종은 달라도 리드타임, 비용, 품질 지표를 관리한 경험으로 연결",
    impact: "high",
    ease: "medium",
    dedupeGroup: "domain_reframe",
    actionFamily: "bridge",
    primaryCluster: "domain_fit",
  },
  ADJACENT_DOMAIN_TARGETING: {
    id: "adjacent_domain_targeting",
    signalKeys: ["SIMPLE__DOMAIN_SHIFT", "TITLE_DOMAIN_SHIFT", "DOMAIN__MISMATCH__JOB_FAMILY"],
    category: "domain_reframe",
    title: "완전히 다른 경험보다 인접 도메인 사례를 먼저 전면 배치",
    task: "지원 직무와 가장 가까운 산업, 고객, 문제 구조를 가진 사례를 대표 경험으로 올리기",
    example: "직접 동일 업종이 아니면 가장 유사한 고객군과 운영 과제를 가진 프로젝트를 먼저 제시",
    impact: "high",
    ease: "medium",
    dedupeGroup: "adjacent_domain",
    actionFamily: "bridge",
    primaryCluster: "domain_fit",
  },
  TIMELINE_EXPLAIN_PACK: {
    id: "timeline_explain_pack",
    signalKeys: ["RISK__TIMELINE_MISMATCH"],
    category: "timeline_story",
    title: "경력 타임라인 공백과 순서를 짧게 설명",
    task: "이직 간격이나 공백이 있으면 이유보다 현재 준비도와 연결되는 한 줄 설명을 추가",
    example: "공백기 동안 관련 역량을 보완했고 현재 바로 수행 가능한 과업에 집중하고 있음을 명시",
    impact: "medium",
    ease: "high",
    dedupeGroup: "timeline_story",
    actionFamily: "timeline_story",
    primaryCluster: "timeline_risk",
  },
  SHORT_TENURE_RESULT_FOCUS: {
    id: "short_tenure_result_focus",
    signalKeys: ["RISK__JOB_HOPPING", "JOB_HOPPING_DENSITY", "RISK__TIMELINE_MISMATCH"],
    category: "stability_story",
    title: "짧은 재직은 기간보다 남긴 결과를 먼저 제시",
    task: "재직 기간 설명보다 짧은 기간 안에 완료한 과업과 성과를 먼저 정리",
    example: "3개월 근무보다 그 안에 프로세스 정리와 오류 감소를 만든 결과를 먼저 제시",
    impact: "high",
    ease: "medium",
    dedupeGroup: "short_tenure",
    actionFamily: "stability_story",
    primaryCluster: "stability_risk",
  },
  STABILITY_NARRATIVE: {
    id: "stability_narrative",
    signalKeys: ["RISK__JOB_HOPPING", "JOB_HOPPING_DENSITY"],
    category: "stability_story",
    title: "이직 빈도보다 일관된 문제 해결 축을 묶어 설명",
    task: "회사 수보다 반복적으로 맡아 온 공통 역할과 성과 패턴을 한 축으로 정리",
    example: "여러 조직에서도 계속 운영 안정화와 데이터 기반 개선을 맡아온 흐름으로 설명",
    impact: "medium",
    ease: "medium",
    dedupeGroup: "stability_story",
    actionFamily: "stability_story",
    primaryCluster: "stability_risk",
  },
  REPRESENTATIVE_CASE_UPGRADE: {
    id: "representative_case_upgrade",
    signalKeys: ["EVIDENCE_THIN", "LOW_CONTENT_DENSITY_RISK", "PROOF_WEAK"],
    category: "evidence_upgrade",
    title: "대표 사례 1개를 골라 문제행동결과 구조로 강화",
    task: "비슷한 항목을 늘리기보다 대표 경험 하나를 문제, 행동, 결과 구조로 다시 쓰기",
    example: "재고 이슈를 발견하고 발주 기준을 조정해 납기 안정화를 만든 사례를 대표로 강화",
    impact: "high",
    ease: "high",
    dedupeGroup: "representative_case",
    actionFamily: "evidence",
    primaryCluster: "evidence_strength",
  },
};
