// src/lib/ontology/taskOntology.js
// PASSMAP Task Ontology v1.1 (precision patch)

export const TASK_ONTOLOGY_V1 = [
  {
    id: "TASK__STRATEGY_PLANNING",
    label: "전략 수립",
    group: "전략/기획",
    synonyms: ["전략 수립", "사업 전략", "중장기 전략", "전사 전략", "strategic planning", "전략 과제", "전략 방향", "성장 전략", "기획안 수립", "사업기획"],
    broadAliases: ["기획", "전략", "사업 기획"],
    negativeCues: ["운영 지원", "단순 실행"],
    weakCues: ["지원", "보조", "참여"],
    strengthBoosters: {
      outcome: ["개선", "향상", "증가", "달성", "최적화", "고도화", "개편"],
      metric: ["kpi", "okr", "지표", "성과", "매출"],
      deliverable: ["전략안", "로드맵", "기획안", "제안서"],
      ownership: ["주도", "리드", "총괄", "오너", "end-to-end"],
    },
  },
  {
    id: "TASK__ROADMAP_PLANNING",
    label: "로드맵 기획",
    group: "전략/기획",
    synonyms: ["로드맵", "연간 계획", "분기 계획", "우선순위 계획", "roadmap"],
    broadAliases: ["기획"],
    weakCues: ["검토", "지원"],
    strengthBoosters: {
      outcome: ["달성", "개편", "고도화"],
      metric: ["kpi", "지표", "성과"],
      deliverable: ["로드맵", "기획안"],
      ownership: ["주도", "리드", "총괄"],
    },
    rewriteGuide: {
      missingHint: "분기/반기 로드맵 문서와 우선순위 의사결정 근거를 bullet로 명시하세요.",
      weakHint: "로드맵 수립에서 본인 결정 범위(우선순위/일정)를 한 줄로 먼저 밝히세요.",
      bulletSkeleton: [
        "[배경/목표] [기간] [우선순위 기준]으로 로드맵을 수립",
        "[본인 역할] [핵심 결정] [산출물] [결과]",
      ],
      exampleStem: "분기 로드맵 수립을 주도하며 우선순위 기준을 정의하고 일정 리스크를 조정했습니다.",
    },
  },
  {
    id: "TASK__MARKET_RESEARCH",
    label: "시장/경쟁 분석",
    group: "전략/기획",
    synonyms: ["시장 조사", "경쟁사 분석", "시장 분석", "market research", "competitive analysis"],
    broadAliases: ["분석"],
    weakCues: ["자료 수집", "보조"],
    strengthBoosters: {
      outcome: ["개선", "고도화"],
      metric: ["전환율", "지표", "성과"],
      deliverable: ["리포트", "보고서", "분석 리포트"],
      ownership: ["주도", "리드"],
    },
  },
  {
    id: "TASK__BUSINESS_MODELING",
    label: "사업/수익 모델링",
    group: "전략/기획",
    synonyms: ["사업 모델", "수익 모델", "비즈니스 모델링", "revenue model"],
    broadAliases: ["기획", "분석"],
    weakCues: ["검토", "참고"],
    strengthBoosters: {
      outcome: ["증가", "개선", "달성"],
      metric: ["매출", "마진", "성과"],
      deliverable: ["기획안", "모델안", "제안서"],
      ownership: ["설계", "주도", "오너"],
    },
  },
  {
    id: "TASK__STRATEGY_EXECUTION_SUPPORT",
    label: "전략 실행 지원",
    group: "전략/기획",
    synonyms: ["전략 실행 지원", "전략 과제 지원", "기획 지원"],
    broadAliases: ["지원", "기획"],
    weakCues: ["지원", "보조", "참여"],
    strengthBoosters: {
      outcome: ["개선"],
      metric: ["지표"],
      deliverable: ["정리 문서"],
      ownership: ["담당"],
    },
  },
  {
    id: "TASK__KPI_DESIGN",
    label: "KPI/지표 설계",
    group: "분석/리포팅",
    synonyms: ["kpi 설계", "okr 설계", "지표 설계", "성과지표", "지표 체계", "성과 관리 체계", "지표 고도화", "kpi 체계"],
    broadAliases: ["분석", "지표", "지표 관리", "지표 운영"],
    weakCues: ["조회", "모니터링"],
    strengthBoosters: {
      outcome: ["향상", "달성", "최적화"],
      metric: ["kpi", "okr", "지표", "성과", "성과 관리"],
      deliverable: ["지표체계", "대시보드", "리포트"],
      ownership: ["정의", "설계", "주도"],
    },
    rewriteGuide: {
      missingHint: "KPI 정의 배경과 목표 수치(기준/목표)를 함께 제시하세요.",
      weakHint: "지표 모니터링이 아닌 지표 설계/정의 기여를 분리해 적으세요.",
      bulletSkeleton: [
        "[지표 정의 대상] KPI를 [기준/목표]로 설계",
        "[정의 이유] [의사결정 활용] [변화 결과]",
      ],
      exampleStem: "핵심 KPI 정의를 주도해 운영 지표 체계를 정리하고 의사결정 기준을 일원화했습니다.",
    },
  },
  {
    id: "TASK__DATA_ANALYSIS",
    label: "데이터 분석",
    group: "분석/리포팅",
    synonyms: ["데이터 분석", "통계 분석", "실적 분석", "성과 분석", "analytics", "지표 분석", "운영 데이터 분석", "데이터 기반 분석"],
    broadAliases: ["분석", "데이터 기반 개선"],
    weakCues: ["조회", "단순 집계"],
    strengthBoosters: {
      outcome: ["개선", "향상", "최적화", "절감"],
      metric: ["kpi", "지표", "성과", "전환율", "매출", "비용"],
      deliverable: ["분석 리포트", "보고서", "대시보드"],
      ownership: ["주도", "리드", "책임"],
    },
    rewriteGuide: {
      missingHint: "분석 과제별 가설-검증-결론 구조를 수치와 함께 제시하세요.",
      weakHint: "단순 조회/집계 표현 대신 분석 의사결정 기여와 결과를 명시하세요.",
      bulletSkeleton: [
        "[문제/가설]을 설정하고 [분석 방법]으로 검증",
        "[본인 기여] [분석 결과] [실행/개선 영향]",
      ],
      exampleStem: "가설 기반 분석을 통해 핵심 전환 저해 요인을 도출하고 개선 우선순위를 제안했습니다.",
    },
  },
  {
    id: "TASK__DASHBOARD_REPORTING",
    label: "리포팅/대시보드",
    group: "분석/리포팅",
    synonyms: ["리포팅", "보고서 작성", "대시보드", "dashboard", "reporting", "kpi 리포팅", "분석 리포트", "성과 리포팅", "운영 리포트"],
    broadAliases: ["분석", "보고"],
    weakCues: ["정리", "취합"],
    strengthBoosters: {
      outcome: ["개선", "향상"],
      metric: ["kpi", "지표", "성과"],
      deliverable: ["보고서", "리포트", "대시보드", "분석 리포트"],
      ownership: ["작성", "자동화", "책임"],
    },
    rewriteGuide: {
      missingHint: "리포트/대시보드 산출물 명칭과 활용 조직(의사결정 수신자)을 적으세요.",
      weakHint: "보고서 작성 사실만이 아니라 보고 이후 개선/의사결정 결과를 연결하세요.",
      bulletSkeleton: [
        "[산출물명] 대시보드/리포트를 구축/개편",
        "[수신자/활용팀] [의사결정 활용] [후속 결과]",
      ],
      exampleStem: "주간 성과 대시보드를 구축해 운영/기획팀의 이슈 우선순위 판단 시간을 단축했습니다.",
    },
  },
  {
    id: "TASK__EXPERIMENT_ANALYSIS",
    label: "실험/A-B 테스트",
    group: "분석/리포팅",
    synonyms: ["a/b 테스트", "실험 설계", "가설 검증", "experiment"],
    broadAliases: ["분석"],
    weakCues: ["테스트 참여", "지원"],
    strengthBoosters: {
      outcome: ["개선", "향상", "증가"],
      metric: ["uplift", "전환율", "성과"],
      deliverable: ["실험 리포트", "보고서"],
      ownership: ["설계", "주도"],
    },
  },
  {
    id: "TASK__ROOT_CAUSE_ANALYSIS",
    label: "원인 분석",
    group: "분석/리포팅",
    synonyms: ["원인 분석", "이슈 분석", "rca", "root cause"],
    broadAliases: ["분석"],
    weakCues: ["확인", "점검"],
    strengthBoosters: {
      outcome: ["개선", "감소", "재발 방지"],
      metric: ["감소율", "지표"],
      deliverable: ["분석 보고서", "제안서"],
      ownership: ["주도", "책임"],
    },
  },
  {
    id: "TASK__PROCESS_OPERATION",
    label: "운영 프로세스 관리",
    group: "운영",
    synonyms: ["운영 관리", "프로세스 운영", "업무 운영", "operation", "운영 프로세스"],
    broadAliases: ["운영", "관리"],
    negativeCues: ["전략 수립", "중장기 전략"],
    weakCues: ["지원", "보조", "대응"],
    strengthBoosters: {
      outcome: ["개선", "향상", "절감", "최적화"],
      metric: ["sla", "처리량", "비용", "지표"],
      deliverable: ["운영 프로세스", "매뉴얼", "보고서"],
      ownership: ["리드", "총괄", "책임"],
    },
  },
  {
    id: "TASK__PROJECT_COORDINATION",
    label: "프로젝트/일정 조율",
    group: "운영",
    synonyms: ["일정 조율", "프로젝트 관리", "협업 조율", "coordination", "pm"],
    broadAliases: ["협업", "관리"],
    weakCues: ["참석", "공유"],
    strengthBoosters: {
      outcome: ["개선", "지연 감소", "달성"],
      metric: ["일정", "납기", "지표"],
      deliverable: ["프로젝트 플랜", "리포트"],
      ownership: ["총괄", "리드"],
    },
  },
  {
    id: "TASK__STAKEHOLDER_COMMUNICATION",
    label: "이해관계자 커뮤니케이션",
    group: "운영",
    synonyms: ["이해관계자 커뮤니케이션", "유관부서 협업", "stakeholder", "cross-functional"],
    broadAliases: ["협업", "커뮤니케이션"],
    weakCues: ["전달", "공유"],
    strengthBoosters: {
      outcome: ["개선", "정렬", "달성"],
      metric: ["응답 시간", "지표"],
      deliverable: ["회의록", "정렬 문서"],
      ownership: ["조율", "합의 주도"],
    },
  },
  {
    id: "TASK__QUALITY_CONTROL",
    label: "품질/이슈 관리",
    group: "운영",
    synonyms: ["품질 관리", "qa", "이슈 관리", "품질 개선"],
    broadAliases: ["운영", "관리"],
    weakCues: ["확인", "점검 지원"],
    strengthBoosters: {
      outcome: ["개선", "감소", "향상"],
      metric: ["불량률", "에러율", "지표"],
      deliverable: ["체크리스트", "품질 리포트"],
      ownership: ["책임", "개선 주도"],
    },
  },
  {
    id: "TASK__FIELD_OPERATION",
    label: "현장 운영",
    group: "운영",
    synonyms: ["현장 운영", "매장 운영", "현장 대응", "운영 지원"],
    broadAliases: ["운영"],
    weakCues: ["지원", "보조", "대응"],
    strengthBoosters: {
      outcome: ["안정화", "개선"],
      metric: ["처리량", "지표"],
      deliverable: ["운영 매뉴얼", "운영 보고서"],
      ownership: ["총괄", "리드"],
    },
  },
  {
    id: "TASK__SERVICE_OPERATION",
    label: "서비스 운영",
    group: "운영",
    synonyms: ["서비스 운영", "고객 운영", "운영 체계 관리"],
    broadAliases: ["운영", "관리"],
    weakCues: ["지원", "참여"],
    strengthBoosters: {
      outcome: ["개선", "향상", "절감"],
      metric: ["지표", "성과", "비용"],
      deliverable: ["운영 프로세스", "매뉴얼"],
      ownership: ["리드", "총괄"],
    },
  },
  {
    id: "TASK__SALES_ENABLEMENT",
    label: "영업 지원/세일즈 운영",
    group: "사업/상업",
    synonyms: ["영업 지원", "세일즈 운영", "sales ops", "영업 기획"],
    broadAliases: ["운영", "지원"],
    weakCues: ["보조", "지원"],
    strengthBoosters: {
      outcome: ["증가", "달성", "향상"],
      metric: ["매출", "수주율", "전환율"],
      deliverable: ["세일즈 자료", "리포트", "대시보드"],
      ownership: ["기획", "운영 주도"],
    },
  },
  {
    id: "TASK__PIPELINE_MANAGEMENT",
    label: "파이프라인/리드 관리",
    group: "사업/상업",
    synonyms: ["파이프라인 관리", "리드 관리", "funnel 관리", "crm 운영"],
    broadAliases: ["관리", "운영"],
    weakCues: ["입력", "조회"],
    strengthBoosters: {
      outcome: ["향상", "증가", "최적화"],
      metric: ["전환율", "리드", "매출"],
      deliverable: ["리포트", "대시보드"],
      ownership: ["관리", "최적화 주도"],
    },
  },
  {
    id: "TASK__PARTNER_MANAGEMENT",
    label: "파트너/채널 관리",
    group: "사업/상업",
    synonyms: ["파트너 관리", "채널 운영", "제휴 관리", "partner management"],
    broadAliases: ["관리", "협업"],
    weakCues: ["응대", "지원"],
    strengthBoosters: {
      outcome: ["매출 증가", "개선", "달성"],
      metric: ["매출", "성과"],
      deliverable: ["제휴안", "리포트"],
      ownership: ["운영 주도", "리드"],
    },
  },
  {
    id: "TASK__PRICING_PROMOTION",
    label: "가격/프로모션 기획",
    group: "사업/상업",
    synonyms: ["가격 정책", "프로모션 기획", "pricing", "promotion", "캠페인 기획", "캠페인 운영", "광고 기획", "프로모션 운영"],
    broadAliases: ["기획", "캠페인", "광고"],
    weakCues: ["참고", "보조"],
    strengthBoosters: {
      outcome: ["증가", "향상", "달성"],
      metric: ["매출", "uplift", "전환율"],
      deliverable: ["프로모션 플랜", "기획안"],
      ownership: ["기획 주도", "리드"],
    },
  },
  {
    id: "TASK__PROCUREMENT_SOURCING",
    label: "구매/소싱",
    group: "구매/SCM",
    synonyms: ["구매", "소싱", "조달", "sourcing", "procurement"],
    broadAliases: ["구매", "관리"],
    weakCues: ["발주 지원", "보조"],
    strengthBoosters: {
      outcome: ["절감", "개선", "달성"],
      metric: ["절감률", "원가", "비용"],
      deliverable: ["소싱 전략", "제안서", "보고서"],
      ownership: ["협상 주도", "소싱 주도", "리드"],
    },
  },
  {
    id: "TASK__STRATEGIC_SOURCING",
    label: "전략 소싱",
    group: "구매/SCM",
    synonyms: ["전략소싱", "전략 소싱", "category sourcing", "sourcing strategy"],
    broadAliases: ["소싱", "구매"],
    weakCues: ["지원", "참여"],
    strengthBoosters: {
      outcome: ["절감", "고도화", "개편"],
      metric: ["절감률", "원가", "성과"],
      deliverable: ["소싱 전략", "카테고리 전략", "제안서"],
      ownership: ["전략 수립", "주도", "오너"],
    },
    rewriteGuide: {
      missingHint: "카테고리별 소싱 전략과 협상 결과(단가/조건 개선)를 명시하세요.",
      weakHint: "단순 구매 운영과 전략소싱(전략수립/협상주도) 역할을 분리해 쓰세요.",
      bulletSkeleton: [
        "[카테고리] 전략소싱 계획 수립 및 협상 주도",
        "[협상 포인트] [조건/단가 변화] [비즈니스 영향]",
      ],
      exampleStem: "카테고리별 전략소싱을 설계하고 협상을 주도해 핵심 조건을 개선했습니다.",
    },
  },
  {
    id: "TASK__ROUTINE_PURCHASING",
    label: "일반 구매/발주",
    group: "구매/SCM",
    synonyms: ["일반 구매", "발주", "구매 요청 처리", "po 처리"],
    broadAliases: ["구매"],
    weakCues: ["지원", "보조", "처리"],
    strengthBoosters: {
      outcome: ["안정화"],
      metric: ["납기", "처리량"],
      deliverable: ["발주서", "구매 리스트"],
      ownership: ["담당"],
    },
  },
  {
    id: "TASK__VENDOR_MANAGEMENT",
    label: "협력사 관리",
    group: "구매/SCM",
    synonyms: ["협력사 관리", "vendor 관리", "supplier 관리", "공급사 관리"],
    broadAliases: ["관리"],
    weakCues: ["응대", "관리 지원"],
    strengthBoosters: {
      outcome: ["개선", "절감", "향상"],
      metric: ["on-time", "불량률", "비용"],
      deliverable: ["평가표", "관리 체계"],
      ownership: ["관리 주도", "리드"],
    },
  },
  {
    id: "TASK__CONTRACT_NEGOTIATION",
    label: "계약/협상",
    group: "구매/SCM",
    synonyms: ["계약 협상", "협상", "계약 관리", "negotiation", "contract"],
    broadAliases: ["협상", "구매"],
    weakCues: ["참석", "지원"],
    strengthBoosters: {
      outcome: ["절감", "개선", "달성"],
      metric: ["절감액", "절감률", "비용"],
      deliverable: ["계약서", "협상안", "제안서"],
      ownership: ["협상 주도", "책임"],
    },
  },
  {
    id: "TASK__DEMAND_FORECAST",
    label: "수요 예측/계획",
    group: "구매/SCM",
    synonyms: ["수요 예측", "수요 계획", "forecast", "demand planning"],
    broadAliases: ["분석", "계획"],
    weakCues: ["집계", "취합"],
    strengthBoosters: {
      outcome: ["최적화", "절감", "달성"],
      metric: ["예측 정확도", "지표", "성과"],
      deliverable: ["수요 계획서", "리포트"],
      ownership: ["예측 모델 운영", "리드"],
    },
  },
  {
    id: "TASK__INVENTORY_OPTIMIZATION",
    label: "재고 최적화",
    group: "구매/SCM",
    synonyms: ["재고 관리", "재고 최적화", "inventory", "안전재고"],
    broadAliases: ["관리", "운영"],
    weakCues: ["재고 확인"],
    strengthBoosters: {
      outcome: ["절감", "최적화", "개선"],
      metric: ["회전율", "재고일수", "비용"],
      deliverable: ["재고 정책", "대시보드"],
      ownership: ["정책 수립", "리드"],
    },
  },
  {
    id: "TASK__PRODUCT_DISCOVERY",
    label: "문제/기회 탐색",
    group: "서비스/프로덕트",
    synonyms: ["문제 정의", "기회 탐색", "고객 인터뷰", "discovery", "user research"],
    broadAliases: ["기획", "분석"],
    weakCues: ["참여", "보조"],
    strengthBoosters: {
      outcome: ["개선", "향상", "정렬"],
      metric: ["전환율", "활성율", "지표"],
      deliverable: ["리서치 리포트", "기획안"],
      ownership: ["탐색 주도", "리드"],
    },
  },
  {
    id: "TASK__REQUIREMENT_DEFINITION",
    label: "요구사항 정의",
    group: "서비스/프로덕트",
    synonyms: ["요구사항 정의", "기능 정의", "spec 작성", "prd", "requirement"],
    broadAliases: ["기획"],
    weakCues: ["정리", "문서화 지원"],
    strengthBoosters: {
      outcome: ["개선", "감소", "향상"],
      metric: ["재작업 감소", "지표"],
      deliverable: ["요구사항 문서", "prd", "기획안"],
      ownership: ["정의 주도", "책임"],
    },
    rewriteGuide: {
      missingHint: "요구사항 문서(PRD/Spec) 작성 범위와 승인/의사결정 참여를 명시하세요.",
      weakHint: "문서 정리 표현 대신 요구사항 정의 책임과 변경 관리 사례를 제시하세요.",
      bulletSkeleton: [
        "[요구사항 대상] PRD/Spec을 정의하고 변경 범위를 관리",
        "[본인 책임] [의사결정 포인트] [개발/운영 영향]",
      ],
      exampleStem: "핵심 요구사항 정의를 주도하고 변경 이슈를 관리해 재작업을 줄였습니다.",
    },
  },
  {
    id: "TASK__BACKLOG_PRIORITIZATION",
    label: "백로그/우선순위 관리",
    group: "서비스/프로덕트",
    synonyms: ["백로그 관리", "우선순위 설정", "스프린트 계획", "prioritization"],
    broadAliases: ["관리", "기획"],
    weakCues: ["업데이트", "지원"],
    strengthBoosters: {
      outcome: ["개선", "향상", "달성"],
      metric: ["cycle time", "지표", "성과"],
      deliverable: ["백로그", "로드맵", "기획안"],
      ownership: ["우선순위 결정", "리드"],
    },
  },
  {
    id: "TASK__UX_IMPROVEMENT",
    label: "UX/서비스 개선",
    group: "서비스/프로덕트",
    synonyms: ["ux 개선", "서비스 개선", "사용성 개선", "개선 과제"],
    broadAliases: ["개선", "기획"],
    weakCues: ["피드백 수집", "보조"],
    strengthBoosters: {
      outcome: ["향상", "증가", "개선"],
      metric: ["nps", "전환율", "지표"],
      deliverable: ["개선안", "실험안", "리포트"],
      ownership: ["개선 주도", "리드"],
    },
  },
  {
    id: "TASK__SERVICE_PLANNING",
    label: "서비스 기획",
    group: "서비스/프로덕트",
    synonyms: ["서비스 기획", "서비스 정책 기획", "service planning"],
    broadAliases: ["기획", "서비스"],
    negativeCues: ["현장 운영", "운영 지원"],
    weakCues: ["지원", "참여"],
    strengthBoosters: {
      outcome: ["개선", "향상", "고도화"],
      metric: ["kpi", "지표", "성과"],
      deliverable: ["정책안", "기획안", "제안서"],
      ownership: ["주도", "리드", "오너"],
    },
    rewriteGuide: {
      missingHint: "서비스 정책/기획 산출물과 적용 후 지표 변화를 함께 제시하세요.",
      weakHint: "운영 지원 표현과 분리해 서비스 기획 의사결정 기여를 명시하세요.",
      bulletSkeleton: [
        "[서비스 과제] 정책/기획안을 설계하고 적용",
        "[본인 결정] [적용 범위] [성과/지표 변화]",
      ],
      exampleStem: "서비스 정책 기획을 주도해 운영 기준을 정립하고 핵심 지표 개선 기반을 만들었습니다.",
    },
  },
];

export const TASK_ONTOLOGY_V1_BY_ID = TASK_ONTOLOGY_V1.reduce((acc, task) => {
  acc[task.id] = task;
  return acc;
}, {});
