export const DATE_FORMAT_TEST_REFERENCE_DATE = "2026-06-04";

export const dateFormatMatrix = Object.freeze([
  {
    id: "date_01_dot_full_year",
    input: "2021.07 ~ 2023.07",
    category: "month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_02_slash_full_year",
    input: "2021/07 ~ 2023/07",
    category: "month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_03_dash_full_year",
    input: "2021-07 ~ 2023-07",
    category: "month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_04_dot_single_month",
    input: "2021.7 ~ 2023.7",
    category: "month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_05_inclusive_24_month_anchor",
    input: "2021.07 ~ 2023.06",
    category: "month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 6,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 24,
      parseWarning: null,
    },
  },
  {
    id: "date_06_short_dot_year",
    input: "21.07 ~ 23.07",
    category: "short_year_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_07_short_slash_year",
    input: "21/07 ~ 23/07",
    category: "short_year_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_08_short_korean_single_month",
    input: "21년 7월 ~ 23년 7월",
    category: "short_year_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_09_short_korean_padded_month",
    input: "21년 07월 ~ 23년 07월",
    category: "short_year_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_10_korean_year_month",
    input: "2021년 7월 ~ 2023년 7월",
    category: "korean_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_11_korean_from_to",
    input: "2021년 07월부터 2023년 07월까지",
    category: "korean_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_12_korean_hire_leave",
    input: "2021년 7월 입사 / 2023년 7월 퇴사",
    category: "korean_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_13_no_space_hyphen",
    input: "2021.07-2023.07",
    category: "separator_variant",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_14_en_dash",
    input: "2021.07 – 2023.07",
    category: "separator_variant",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_15_em_dash",
    input: "2021.07 — 2023.07",
    category: "separator_variant",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_16_tilde",
    input: "2021.07 ~ 2023.07",
    category: "separator_variant",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "date_17_wave_dash",
    input: "2021.07 ∼ 2023.07",
    category: "separator_variant",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 25,
      parseWarning: null,
    },
  },
  {
    id: "present_01_korean_current",
    input: "2021.07 ~ 현재",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_02_korean_employed_compact",
    input: "2021.07 ~ 재직중",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_03_korean_employed_spaced",
    input: "2021.07 ~ 재직 중",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_04_english_present",
    input: "2021.07 ~ Present",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_05_english_now",
    input: "2021.07 ~ now",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_06_korean_current_employed",
    input: "2021.07 ~ 현재 재직",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_07_hire_to_current",
    input: "2021.07 입사 ~ 현재",
    category: "current_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: null,
    },
  },
  {
    id: "present_08_open_ended",
    input: "2021.07 ~",
    category: "current_range_open_ended",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2026,
      endMonth: 6,
      isCurrent: true,
      datePrecision: "month",
      durationMonthsInclusive: 60,
      parseWarning: "open_ended_current_assumed",
    },
  },
  {
    id: "date_year_only_01_plain_tilde",
    input: "2021 ~ 2023",
    category: "year_only_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "year",
      durationMonthsRange: { min: 13, max: 36 },
      parseWarning: "month_missing",
    },
  },
  {
    id: "date_year_only_02_korean",
    input: "2021년 ~ 2023년",
    category: "year_only_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "year",
      durationMonthsRange: { min: 13, max: 36 },
      parseWarning: "month_missing",
    },
  },
  {
    id: "date_year_only_03_hyphen",
    input: "2021 - 2023",
    category: "year_only_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "year",
      durationMonthsRange: { min: 13, max: 36 },
      parseWarning: "month_missing",
    },
  },
  {
    id: "date_year_only_04_hire_leave",
    input: "2021 입사 / 2023 퇴사",
    category: "year_only_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "year",
      durationMonthsRange: { min: 13, max: 36 },
      parseWarning: "month_missing",
    },
  },
  {
    id: "date_partial_01_missing_end_month",
    input: "2021.07 ~ 2023",
    category: "partial_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "partial_month",
      durationMonthsRange: { min: 19, max: 30 },
      parseWarning: "end_month_missing",
    },
  },
  {
    id: "date_partial_02_missing_start_month",
    input: "2021 ~ 2023.07",
    category: "partial_month_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "partial_month",
      durationMonthsRange: { min: 20, max: 31 },
      parseWarning: "start_month_missing",
    },
  },
  {
    id: "date_partial_03_korean_missing_end_month",
    input: "2021년 7월 ~ 2023년",
    category: "partial_month_range",
    expected: {
      startYear: 2021,
      startMonth: 7,
      endYear: 2023,
      endMonth: null,
      isCurrent: false,
      datePrecision: "partial_month",
      durationMonthsRange: { min: 19, max: 30 },
      parseWarning: "end_month_missing",
    },
  },
  {
    id: "date_partial_04_korean_missing_start_month",
    input: "2021년 ~ 2023년 7월",
    category: "partial_month_range",
    expected: {
      startYear: 2021,
      startMonth: null,
      endYear: 2023,
      endMonth: 7,
      isCurrent: false,
      datePrecision: "partial_month",
      durationMonthsRange: { min: 20, max: 31 },
      parseWarning: "start_month_missing",
    },
  },
  {
    id: "gap_01_explicit_gap",
    input: "2019.08 ~ 2023.09 공백",
    category: "gap_range",
    expected: {
      startYear: 2019,
      startMonth: 8,
      endYear: 2023,
      endMonth: 9,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 50,
      parseWarning: null,
      timelineKind: "gap",
    },
  },
  {
    id: "gap_02_career_exploration_partial",
    input: "2019년 하반기 ~ 2023년 9월 진로탐색",
    category: "gap_range_partial",
    expected: {
      startYear: 2019,
      startMonth: null,
      endYear: 2023,
      endMonth: 9,
      isCurrent: false,
      datePrecision: "partial_month",
      durationMonthsRange: { min: 46, max: 51 },
      parseWarning: "start_month_imprecise",
      timelineKind: "gap",
    },
  },
  {
    id: "gap_03_personal_reason",
    input: "2019.08-2023.09 개인 사유",
    category: "gap_range",
    expected: {
      startYear: 2019,
      startMonth: 8,
      endYear: 2023,
      endMonth: 9,
      isCurrent: false,
      datePrecision: "month",
      durationMonthsInclusive: 50,
      parseWarning: null,
      timelineKind: "gap",
    },
  },
]);
