export const employmentTypeMatrix = Object.freeze([
  {
    id: "employment_01_full_time",
    inputLabels: ["정규직", "full-time", "full time", "풀타임", "상근"],
    normalizedEmploymentType: "full_time",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 1.0,
      shortTenureApplicable: true,
      riskSignalsPossible: [],
      notes: "일반적인 정식 경력으로 계산한다.",
    },
  },
  {
    id: "employment_02_contract",
    inputLabels: ["계약직", "계약직원", "fixed-term", "contract"],
    normalizedEmploymentType: "contract",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.85,
      shortTenureApplicable: "contextual",
      riskSignalsPossible: ["contract_continuity_risk"],
      notes: "기간제 경력으로 계산하되 반복 계약과 직무 연속성은 별도 해석한다.",
    },
  },
  {
    id: "employment_03_internship",
    inputLabels: ["인턴", "intern", "internship"],
    normalizedEmploymentType: "internship",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.4,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "실무 노출 신호로 보되 정규직과 같은 깊이로 평가하지 않는다.",
    },
  },
  {
    id: "employment_04_experience_internship",
    inputLabels: ["체험형 인턴", "체험 인턴", "experience internship"],
    normalizedEmploymentType: "experience_internship",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.35,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "직무 탐색/노출 신호이며 경력 깊이는 낮게 본다.",
    },
  },
  {
    id: "employment_05_conversion_internship",
    inputLabels: ["채용연계형 인턴", "전환형 인턴", "conversion internship"],
    normalizedEmploymentType: "conversion_internship",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.55,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "일반 인턴보다 강한 실무/평가 신호지만 short tenure 리스크로 보지 않는다.",
    },
  },
  {
    id: "employment_06_dispatch",
    inputLabels: ["파견직", "파견", "dispatch", "agency worker"],
    normalizedEmploymentType: "dispatch",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.75,
      shortTenureApplicable: "contextual",
      riskSignalsPossible: ["employment_stability_risk"],
      notes: "근무 현장과 소속 구조를 분리해 보되 경력에서 제외하지 않는다.",
    },
  },
  {
    id: "employment_07_freelance",
    inputLabels: ["프리랜서", "freelance", "freelancer"],
    normalizedEmploymentType: "freelance",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.65,
      shortTenureApplicable: false,
      riskSignalsPossible: ["scope_clarity_risk", "continuity_risk"],
      notes: "프로젝트 산출물과 기간 밀도를 확인해야 하며 공백으로 처리하지 않는다.",
    },
  },
  {
    id: "employment_08_self_employed",
    inputLabels: ["개인사업자", "자영업", "self-employed", "sole proprietor"],
    normalizedEmploymentType: "founder_or_self_employed",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: "contextual",
      shortTenureApplicable: false,
      riskSignalsPossible: ["business_scope_clarity_risk"],
      notes: "사업 실체와 직무 관련 산출물이 있으면 경력/신호로 인정한다.",
    },
  },
  {
    id: "employment_09_founder",
    inputLabels: ["창업", "대표", "founder", "startup founder"],
    normalizedEmploymentType: "founder_or_self_employed",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: "contextual",
      shortTenureApplicable: false,
      riskSignalsPossible: ["business_outcome_clarity_risk"],
      notes: "창업/대표 경험은 공백이 아니며 역할 범위, 성과, 지속성을 함께 본다.",
    },
  },
  {
    id: "employment_10_part_time_job",
    inputLabels: ["아르바이트", "알바", "part-time job"],
    normalizedEmploymentType: "part_time",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.3,
      shortTenureApplicable: false,
      riskSignalsPossible: ["depth_limit_risk"],
      notes: "관련 직무/산업이면 보조 신호로 반영하되 정규직과 동일하게 보지 않는다.",
    },
  },
  {
    id: "employment_11_part_time",
    inputLabels: ["파트타임", "part-time", "시간제"],
    normalizedEmploymentType: "part_time",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.3,
      shortTenureApplicable: false,
      riskSignalsPossible: ["depth_limit_risk"],
      notes: "근무 밀도와 직무 관련성에 따라 보조 경력 또는 신호로 본다.",
    },
  },
  {
    id: "employment_12_outsourcing",
    inputLabels: ["외주", "용역", "outsourcing"],
    normalizedEmploymentType: "project_contract",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.6,
      shortTenureApplicable: false,
      riskSignalsPossible: ["scope_clarity_risk"],
      notes: "외주는 프로젝트 계약성 경력으로 보고 산출물/범위를 확인한다.",
    },
  },
  {
    id: "employment_13_project_contract",
    inputLabels: ["프로젝트 계약", "프로젝트 단위 계약", "project contract"],
    normalizedEmploymentType: "project_contract",
    expected: {
      countsAsExperience: true,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0.6,
      shortTenureApplicable: false,
      riskSignalsPossible: ["continuity_risk", "scope_clarity_risk"],
      notes: "프로젝트 기간은 중복 합산하지 않고 산출물 기준으로 해석한다.",
    },
  },
  {
    id: "employment_14_trainee",
    inputLabels: ["교육생", "trainee", "수강생"],
    normalizedEmploymentType: "training",
    expected: {
      countsAsExperience: false,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "실무 경력이 아니라 학습/준비 신호로만 반영한다.",
    },
  },
  {
    id: "employment_15_bootcamp",
    inputLabels: ["부트캠프", "bootcamp", "집중 교육"],
    normalizedEmploymentType: "training",
    expected: {
      countsAsExperience: false,
      countsAsGap: false,
      countsAsSignal: true,
      experienceWeight: 0,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "부트캠프는 실무 경력으로 합산하지 않고 역량 전환 신호로 본다.",
    },
  },
  {
    id: "employment_16_gap",
    inputLabels: ["공백", "경력 공백", "gap"],
    normalizedEmploymentType: "gap",
    expected: {
      countsAsExperience: false,
      countsAsGap: true,
      countsAsSignal: false,
      experienceWeight: 0,
      shortTenureApplicable: false,
      riskSignalsPossible: ["career_gap_risk"],
      notes: "경력 기간으로 합산하지 않고 gapMonths와 riskSignals에 반영한다.",
    },
  },
  {
    id: "employment_17_career_exploration",
    inputLabels: ["진로탐색", "커리어 탐색", "career exploration"],
    normalizedEmploymentType: "gap",
    expected: {
      countsAsExperience: false,
      countsAsGap: true,
      countsAsSignal: "contextual",
      experienceWeight: 0,
      shortTenureApplicable: false,
      riskSignalsPossible: ["career_direction_risk"],
      notes: "공백으로 보되 탐색 활동 증거가 있으면 신호로 별도 표시할 수 있다.",
    },
  },
  {
    id: "employment_18_military_service",
    inputLabels: ["군복무", "군 복무", "military service"],
    normalizedEmploymentType: "military_service",
    expected: {
      countsAsExperience: false,
      countsAsGap: false,
      countsAsSignal: "contextual",
      experienceWeight: 0,
      shortTenureApplicable: false,
      riskSignalsPossible: [],
      notes: "일반 직무 경력도 공백도 아니며 특수 타임라인 구간으로 처리한다.",
    },
  },
  {
    id: "employment_19_leave_of_absence",
    inputLabels: ["휴직", "leave of absence", "육아휴직", "병가"],
    normalizedEmploymentType: "leave_of_absence",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: "contextual",
      experienceWeight: "contextual",
      shortTenureApplicable: false,
      riskSignalsPossible: ["availability_or_continuity_risk"],
      notes: "휴직은 무조건 공백으로 처리하지 않고 재직 유지 여부와 역할 중단을 분리한다.",
    },
  },
  {
    id: "employment_20_unpaid_activity",
    inputLabels: ["무급 활동", "대외활동", "동아리", "unpaid activity"],
    normalizedEmploymentType: "unpaid_activity",
    expected: {
      countsAsExperience: "contextual",
      countsAsGap: false,
      countsAsSignal: "contextual",
      experienceWeight: "contextual_low",
      shortTenureApplicable: false,
      riskSignalsPossible: ["professional_depth_risk"],
      notes: "직무 관련 산출물이 있으면 신호로 보되 일반 실무 경력으로 과대평가하지 않는다.",
    },
  },
]);
