export const expectedOwnershipSeniorityProfiles = Object.freeze({
  ownership_01_accounting_admin_excel_entry: {
    artifactType: "spreadsheet",
    roleFamily: "accounting_admin",
    seniorityLevel: "junior_support",
    ownershipLevel: "support",
    judgmentLevel: "low",
    domainDepth: "basic_transaction_organization",
    evidenceLevel: "explicit",
    shouldNotInfer: [
      "senior_accounting_judgment",
      "financial_analysis",
      "closing_ownership",
      "audit_response_lead",
    ],
    strengthSignals: [
      "document_organization",
      "transaction_data_entry",
      "evidence_file_management",
    ],
    riskSignals: [
      "limited_ownership_evidence",
      "judgment_scope_unclear",
    ],
    explanationBoundary: "엑셀 산출물이 있더라도 정해진 양식 입력과 증빙 정리 중심이면 시니어 회계 판단으로 과대평가하지 않는다.",
    confidence: "medium_high",
  },
  ownership_02_senior_accountant_excel_close_pack: {
    artifactType: "spreadsheet",
    roleFamily: "accounting_finance",
    seniorityLevel: "senior_practitioner",
    ownershipLevel: "lead",
    judgmentLevel: "high",
    domainDepth: "monthly_close_and_account_reconciliation",
    evidenceLevel: "explicit",
    shouldNotInfer: [
      "simple_admin_support",
      "data_entry_only",
    ],
    strengthSignals: [
      "account_reconciliation",
      "closing_review",
      "variance_analysis",
      "audit_evidence_preparation",
      "financial_issue_explanation",
    ],
    riskSignals: [],
    explanationBoundary: "같은 엑셀이라도 계정 대사, 조정 판단, 감사 대응, 재무 영향 설명 근거가 있으면 시니어 회계 실무로 본다.",
    confidence: "high",
  },
  ownership_03_finance_analyst_excel_forecast_model: {
    artifactType: "spreadsheet",
    roleFamily: "finance_analysis",
    seniorityLevel: "analyst_or_mid",
    ownershipLevel: "recommend",
    judgmentLevel: "medium_high",
    domainDepth: "forecasting_and_scenario_analysis",
    evidenceLevel: "explicit",
    shouldNotInfer: [
      "accounting_close_ownership",
      "payroll_operation",
    ],
    strengthSignals: [
      "forecast_modeling",
      "scenario_analysis",
      "business_assumption_structuring",
      "executive_decision_support",
    ],
    riskSignals: [
      "actual_pnl_ownership_unclear",
    ],
    explanationBoundary: "엑셀 사용이 회계처리인지 재무분석인지 구분해야 하며, 예측/민감도/시나리오 근거가 있으면 FP&A 성격으로 본다.",
    confidence: "high",
  },
  ownership_04_hr_ops_excel_payroll_support: {
    artifactType: "spreadsheet",
    roleFamily: "hr_operations",
    seniorityLevel: "junior_or_mid_support",
    ownershipLevel: "support",
    judgmentLevel: "medium_low",
    domainDepth: "payroll_input_operations",
    evidenceLevel: "explicit",
    shouldNotInfer: [
      "accounting_finance",
      "senior_payroll_policy_owner",
      "labor_law_judgment_owner",
    ],
    strengthSignals: [
      "payroll_input_preparation",
      "attendance_data_checking",
      "cross_department_follow_up",
      "data_quality_check",
    ],
    riskSignals: [
      "policy_judgment_scope_unclear",
    ],
    explanationBoundary: "근태/급여 기초자료 엑셀은 회계 결산이 아니라 HR 운영 신호로 분류한다.",
    confidence: "medium_high",
  },
  ownership_05_product_ops_excel_funnel_report: {
    artifactType: "spreadsheet",
    roleFamily: "product_operations",
    seniorityLevel: "mid_practitioner",
    ownershipLevel: "recommend_and_follow_up",
    judgmentLevel: "medium_high",
    domainDepth: "funnel_diagnosis_and_product_ops",
    evidenceLevel: "explicit",
    shouldNotInfer: [
      "accounting_finance",
      "data_scientist",
    ],
    strengthSignals: [
      "funnel_analysis",
      "customer_dropoff_diagnosis",
      "product_improvement_recommendation",
      "post_release_monitoring",
      "cross_functional_collaboration",
    ],
    riskSignals: [
      "experiment_design_depth_unclear",
    ],
    explanationBoundary: "엑셀 리포트가 제품/운영 개선 의사결정에 연결되면 단순 사무가 아니라 서비스 운영/제품 운영 신호로 본다.",
    confidence: "high",
  },
  ownership_06_ambiguous_excel_only: {
    artifactType: "spreadsheet",
    roleFamily: "unknown_admin_support",
    seniorityLevel: "unknown",
    ownershipLevel: "unknown",
    judgmentLevel: "unknown",
    domainDepth: "insufficient_evidence",
    evidenceLevel: "inferred_weak",
    shouldNotInfer: [
      "accounting_finance",
      "finance_analysis",
      "product_operations",
      "senior_ownership",
      "domain_expertise",
    ],
    strengthSignals: [
      "spreadsheet_usage",
      "basic_data_organization",
    ],
    riskSignals: [
      "insufficient_ownership_evidence",
      "domain_context_missing",
      "seniority_unclear",
    ],
    explanationBoundary: "엑셀을 사용했다는 말만으로 회계, 재무분석, 운영기획, 시니어 역량을 추론하면 안 된다.",
    confidence: "low",
  },
});
