export const expectedDateEmploymentProfiles = Object.freeze({
  combined_01_intern_contract_fulltime_sequence: {
    totalCalendarMonths: 60,
    weightedExperienceMonths: "contextual",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: "full_time",
    primaryRoleFamily: "service_planning",
    employmentTimeline: [
      {
        employmentType: "internship",
        durationMonths: 6,
        experienceWeight: 0.4,
        shortTenureApplicable: false,
      },
      {
        employmentType: "contract",
        durationMonths: 18,
        experienceWeight: 0.85,
        shortTenureApplicable: "contextual",
      },
      {
        employmentType: "full_time",
        durationMonths: 36,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
    ],
    expectedWarnings: [],
  },
  combined_02_freelance_to_fulltime: {
    totalCalendarMonths: 58,
    weightedExperienceMonths: "contextual",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: null,
    primaryRoleFamily: "operations",
    employmentTimeline: [
      {
        employmentType: "freelance",
        durationMonths: 18,
        experienceWeight: 0.65,
        shortTenureApplicable: false,
      },
      {
        employmentType: "full_time",
        durationMonths: 40,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
    ],
    expectedWarnings: ["freelance_scope_requires_evidence"],
  },
  combined_03_bootcamp_to_fulltime: {
    totalCalendarMonths: 42,
    weightedExperienceMonths: "36 full-time months; bootcamp is signal only",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: null,
    primaryRoleFamily: "data_analysis",
    employmentTimeline: [
      {
        employmentType: "training",
        durationMonths: 6,
        experienceWeight: 0,
        shortTenureApplicable: false,
        countsAsExperience: false,
      },
      {
        employmentType: "full_time",
        durationMonths: 36,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
    ],
    expectedWarnings: ["training_not_counted_as_work_experience"],
  },
  combined_04_gap_contract_fulltime: {
    totalCalendarMonths: 59,
    weightedExperienceMonths: "42 work months with separate 17 gap months",
    hasGap: true,
    gapMonths: 17,
    shortTenureCount: 0,
    currentEmploymentType: null,
    primaryRoleFamily: "hr_recruiting",
    employmentTimeline: [
      {
        employmentType: "gap",
        durationMonths: 17,
        experienceWeight: 0,
        shortTenureApplicable: false,
        countsAsGap: true,
      },
      {
        employmentType: "contract",
        durationMonths: 12,
        experienceWeight: 0.85,
        shortTenureApplicable: "contextual",
      },
      {
        employmentType: "full_time",
        durationMonths: 30,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
    ],
    expectedWarnings: ["gap_not_counted_as_experience"],
  },
  combined_05_military_activity_fulltime: {
    totalCalendarMonths: 75,
    weightedExperienceMonths: "48 full-time months; military and unpaid activity are separate timeline signals",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: null,
    primaryRoleFamily: "operations",
    employmentTimeline: [
      {
        employmentType: "military_service",
        durationMonths: 21,
        experienceWeight: 0,
        shortTenureApplicable: false,
        countsAsGap: false,
      },
      {
        employmentType: "unpaid_activity",
        durationMonths: 6,
        experienceWeight: "contextual_low",
        shortTenureApplicable: false,
      },
      {
        employmentType: "full_time",
        durationMonths: 48,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
    ],
    expectedWarnings: ["military_service_not_counted_as_general_work_experience"],
  },
  combined_06_leave_inside_fulltime: {
    totalCalendarMonths: 78,
    weightedExperienceMonths: "contextual active work months; leave is not a gap",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: "full_time",
    primaryRoleFamily: "product_operations",
    employmentTimeline: [
      {
        employmentType: "full_time",
        durationMonths: 78,
        experienceWeight: 1.0,
        shortTenureApplicable: true,
      },
      {
        employmentType: "leave_of_absence",
        durationMonths: 6,
        experienceWeight: "contextual",
        shortTenureApplicable: false,
        countsAsGap: false,
      },
    ],
    expectedWarnings: ["leave_of_absence_not_counted_as_gap"],
  },
  combined_07_overlapping_project_contracts: {
    totalCalendarMonths: 15,
    weightedExperienceMonths: "deduplicated project-contract duration * 0.6",
    hasGap: false,
    shortTenureCount: 0,
    currentEmploymentType: null,
    primaryRoleFamily: "content_service",
    employmentTimeline: [
      {
        employmentType: "project_contract",
        durationMonths: 6,
        experienceWeight: 0.6,
        shortTenureApplicable: false,
      },
      {
        employmentType: "project_contract",
        durationMonths: 6,
        experienceWeight: 0.6,
        shortTenureApplicable: false,
        overlapsWith: ["커리어 서비스 리서치 프로젝트"],
      },
      {
        employmentType: "project_contract",
        durationMonths: 6,
        experienceWeight: 0.6,
        shortTenureApplicable: false,
      },
    ],
    expectedWarnings: ["overlapping_projects_must_not_be_double_counted"],
  },
});
