export const expectedEmploymentProfiles = Object.freeze({
  employment_01_full_time: {
    normalizedEmploymentType: "full_time",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 1.0,
    shortTenureApplicable: true,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 1.0",
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_02_contract: {
    normalizedEmploymentType: "contract",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.85,
    shortTenureApplicable: "contextual",
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.85",
      gapMonths: 0,
      riskSignals: ["contract_continuity_risk"],
    },
  },
  employment_03_internship: {
    normalizedEmploymentType: "internship",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.4,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.4",
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_04_experience_internship: {
    normalizedEmploymentType: "experience_internship",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.35,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.35",
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_05_conversion_internship: {
    normalizedEmploymentType: "conversion_internship",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.55,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.55",
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_06_dispatch: {
    normalizedEmploymentType: "dispatch",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.75,
    shortTenureApplicable: "contextual",
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.75",
      gapMonths: 0,
      riskSignals: ["employment_stability_risk"],
    },
  },
  employment_07_freelance: {
    normalizedEmploymentType: "freelance",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.65,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.65",
      gapMonths: 0,
      riskSignals: ["scope_clarity_risk", "continuity_risk"],
    },
  },
  employment_08_self_employed: {
    normalizedEmploymentType: "founder_or_self_employed",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: "contextual",
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual",
      weightedExperienceMonths: "contextual",
      gapMonths: 0,
      riskSignals: ["business_scope_clarity_risk"],
    },
  },
  employment_09_founder: {
    normalizedEmploymentType: "founder_or_self_employed",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: "contextual",
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual",
      weightedExperienceMonths: "contextual",
      gapMonths: 0,
      riskSignals: ["business_outcome_clarity_risk"],
    },
  },
  employment_10_part_time_job: {
    normalizedEmploymentType: "part_time",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.3,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual",
      weightedExperienceMonths: "duration * 0.3 when relevant",
      gapMonths: 0,
      riskSignals: ["depth_limit_risk"],
    },
  },
  employment_11_part_time: {
    normalizedEmploymentType: "part_time",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.3,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual",
      weightedExperienceMonths: "duration * 0.3 when relevant",
      gapMonths: 0,
      riskSignals: ["depth_limit_risk"],
    },
  },
  employment_12_outsourcing: {
    normalizedEmploymentType: "project_contract",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.6,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "full_duration",
      weightedExperienceMonths: "duration * 0.6",
      gapMonths: 0,
      riskSignals: ["scope_clarity_risk"],
    },
  },
  employment_13_project_contract: {
    normalizedEmploymentType: "project_contract",
    countsAsExperience: true,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0.6,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "deduplicated_calendar_duration",
      weightedExperienceMonths: "deduplicated_duration * 0.6",
      gapMonths: 0,
      riskSignals: ["continuity_risk", "scope_clarity_risk"],
    },
  },
  employment_14_trainee: {
    normalizedEmploymentType: "training",
    countsAsExperience: false,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: 0,
      weightedExperienceMonths: 0,
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_15_bootcamp: {
    normalizedEmploymentType: "training",
    countsAsExperience: false,
    countsAsGap: false,
    countsAsSignal: true,
    experienceWeight: 0,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: 0,
      weightedExperienceMonths: 0,
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_16_gap: {
    normalizedEmploymentType: "gap",
    countsAsExperience: false,
    countsAsGap: true,
    countsAsSignal: false,
    experienceWeight: 0,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: 0,
      weightedExperienceMonths: 0,
      gapMonths: "full_duration",
      riskSignals: ["career_gap_risk"],
    },
  },
  employment_17_career_exploration: {
    normalizedEmploymentType: "gap",
    countsAsExperience: false,
    countsAsGap: true,
    countsAsSignal: "contextual",
    experienceWeight: 0,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: 0,
      weightedExperienceMonths: 0,
      gapMonths: "full_duration",
      riskSignals: ["career_direction_risk"],
    },
  },
  employment_18_military_service: {
    normalizedEmploymentType: "military_service",
    countsAsExperience: false,
    countsAsGap: false,
    countsAsSignal: "contextual",
    experienceWeight: 0,
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: 0,
      weightedExperienceMonths: 0,
      gapMonths: 0,
      riskSignals: [],
    },
  },
  employment_19_leave_of_absence: {
    normalizedEmploymentType: "leave_of_absence",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: "contextual",
    experienceWeight: "contextual",
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual_active_work_months_only",
      weightedExperienceMonths: "contextual",
      gapMonths: 0,
      riskSignals: ["availability_or_continuity_risk"],
    },
  },
  employment_20_unpaid_activity: {
    normalizedEmploymentType: "unpaid_activity",
    countsAsExperience: "contextual",
    countsAsGap: false,
    countsAsSignal: "contextual",
    experienceWeight: "contextual_low",
    shortTenureApplicable: false,
    expectedCareerProfileImpact: {
      experienceMonths: "contextual",
      weightedExperienceMonths: "contextual_low",
      gapMonths: 0,
      riskSignals: ["professional_depth_risk"],
    },
  },
});
