export const expectedCareerProfiles = Object.freeze([
  {
    caseId: "golden_01_direct_service_planner",
    expectedCareerProfile: {
      totalExperienceMonths: 62,
      directlyRelevantMonths: 62,
      adjacentRelevantMonths: 0,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 0,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "service_planning",
      secondaryRoleFamilies: ["product_planning_pm", "operations"],
      industryDomains: ["education_career", "platform", "hr_recruiting"],
      adjacentIndustryDomains: ["content_service"],
      strengthSignals: [
        "서비스기획과 product_planning_pm 신호가 최신 경력과 이전 경력에 모두 존재한다",
        "B2B SaaS 기반 커리어 플랫폼과 교육/커리어 서비스 산업 맥락이 명확하다",
        "온보딩 퍼널, 상담 전환율, 운영 시간 절감 등 정량 성과가 있다",
      ],
      riskSignals: [
        "대규모 조직의 전사 PO보다 서비스기획 실무/주니어-미들 ownership으로 해석해야 한다",
      ],
      evidenceAnchors: [
        "넥스트커리어랩 / 서비스기획자 / 2020.03 ~ 2023.08",
        "B2B SaaS 기반 커리어 플랫폼의 이력서 진단, 상담 예약, 기업 관리자 화면 요구사항",
        "지원자 온보딩 퍼널을 개편해 무료 진단 완료율을 38%에서 54%로 높이고 유료 상담 전환율을 11%에서 18%로 개선",
        "상담 배정 템플릿과 운영 플로우를 표준화해 담당자 수기 확인 시간을 월 32시간 줄임",
      ],
      confidence: "high",
      rationale:
        "김서윤은 서비스기획을 중심으로 product_planning_pm과 operations 신호가 함께 누적된 정석 유관 경력자다. CareerProfile 기준에서는 JD 적합도가 아니라 커리어 플랫폼/교육 커리어 산업의 서비스기획 경력 정체성이 기준선이다.",
    },
  },
  {
    caseId: "golden_02_career_consulting_to_service_planning",
    expectedCareerProfile: {
      totalExperienceMonths: 70,
      directlyRelevantMonths: 48,
      adjacentRelevantMonths: 22,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 0,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "career_consulting",
      secondaryRoleFamilies: ["operations", "service_planning", "content_strategy"],
      industryDomains: ["education_career", "hr_recruiting", "content_service"],
      adjacentIndustryDomains: ["platform"],
      strengthSignals: [
        "이직코칭 운영은 단순 CS가 아니라 진단, 매칭, 일정, 후속 과제까지 포함한 career_consulting operations다",
        "접수 분류와 배정 SOP 재설계가 service_planning 전환 가능성을 만든다",
        "콘텐츠 운영과 성과 리포트 경험이 content_strategy 신호를 보강한다",
      ],
      riskSignals: [
        "정식 서비스기획 title은 없으므로 service_planning은 secondary로 두는 것이 보수적이다",
        "제품 로드맵 ownership은 운영 프로세스 개선에서 간접적으로 드러난다",
      ],
      evidenceAnchors: [
        "박민재 / 트루커리어파트너스 / 이직코칭 운영 매니저 / 2021.01 ~ 2024.12",
        "첫 코칭까지 걸리는 평균 리드타임을 5.1일에서 2.0일로 줄임",
        "반복 문의와 상담 이슈를 콘텐츠 개선 요구사항으로 전달",
        "잡콘텐츠스튜디오 / 콘텐츠 운영 담당자 / 2019.03 ~ 2020.12",
      ],
      confidence: "high",
      rationale:
        "박민재는 career_consulting과 operations가 중심이고, 콘텐츠 운영과 프로세스 개선을 통해 service_planning 및 content_strategy로 전환 가능한 경력자다. 상담/코칭을 단순 고객응대로 낮추면 기준선 해석이 깨진다.",
    },
  },
  {
    caseId: "golden_03_manufacturing_quality_to_bio_operations",
    expectedCareerProfile: {
      totalExperienceMonths: 67,
      directlyRelevantMonths: 48,
      adjacentRelevantMonths: 19,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 1,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "production_quality",
      secondaryRoleFamilies: ["process_management", "risk_management", "operations"],
      industryDomains: ["manufacturing"],
      adjacentIndustryDomains: ["bio_pharma"],
      strengthSignals: [
        "생산계획, 작업지시, 공정별 실적, 납기 리스크 점검이 process_management 신호를 만든다",
        "불량 재작업 원인 기록과 검사 체크리스트 개선은 production_quality 신호다",
        "품질 이슈 발생 시 원인 확인과 임시 대응 조율은 risk_management 신호다",
      ],
      riskSignals: [
        "바이오의약품 직접 경험은 없으므로 bio_pharma는 adjacentIndustryDomains로 둔다",
        "품질검사 보조 경력은 최신 생산관리 경력보다 낮은 weight로 해석해야 한다",
      ],
      evidenceAnchors: [
        "이도현 / 한성정밀 / 생산관리 담당자 / 2018.04 ~ 2022.03",
        "일일 생산계획, 작업지시, 공정별 실적 집계, 납기 리스크 점검",
        "월간 재작업률을 14% 낮춤",
        "세영테크 / 품질검사 보조 / 2016.08 ~ 2018.02",
      ],
      confidence: "high",
      rationale:
        "이도현은 manufacturing 기반 production_quality와 process_management가 중심인 경력자다. 제조 현장 경력으로만 낮추지 않고 바이오 생산/품질 운영과의 adjacent 관계를 기준선에 남긴다.",
    },
  },
  {
    caseId: "golden_04_gap_short_tenure_transition",
    expectedCareerProfile: {
      totalExperienceMonths: 29,
      directlyRelevantMonths: 17,
      adjacentRelevantMonths: 12,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 50,
      shortTenureCount: 1,
      recentExperienceWeight: "medium",
      primaryRoleFamily: "production_quality",
      secondaryRoleFamilies: ["process_management", "risk_management", "career_consulting"],
      industryDomains: ["bio_pharma"],
      adjacentIndustryDomains: ["education_career", "hr_recruiting"],
      strengthSignals: [
        "바이오의약품 생산 엔지니어 경력에서 GMP 배치 기록, 공정 이상 보고, 설비 운전 신호가 명확하다",
        "최근 커리어 리서치 경험은 직무, 산업, 리스크 신호를 분류한 분석 경험이다",
        "생산 운영과 커리어 리서치가 서로 다른 축이지만 각각의 evidence가 존재한다",
      ],
      riskSignals: [
        "약 50개월 공백은 별도 리스크로 표시해야 한다",
        "최근 커리어 리서치 어시스턴트 경력은 12개월로 짧아 shortTenureCount에 반영한다",
        "생산/품질 축과 커리어 리서치 축 사이의 방향성 전환 리스크가 있다",
      ],
      evidenceAnchors: [
        "정하늘 / 삼성바이오로직스 / 바이오의약품 생산 엔지니어 / 2018.03 ~ 2019.07",
        "바이오의약품 생산 설비 운전, GMP 배치 기록, 공정 이상 보고",
        "커리어인사이트 / 커리어 리서치 어시스턴트 / 2023.10 ~ 2024.09",
        "180건의 후보자 사례를 정리하고 경력 공백, 짧은 재직, 산업 전환 패턴을 분류",
      ],
      confidence: "medium",
      rationale:
        "정하늘은 bio_pharma 생산/품질 경험과 최근 career_consulting 인접 리서치 경험을 모두 가진 전환형 경력자다. 공백과 짧은 재직은 리스크지만 전체 CareerProfile을 탈락 사유 하나로 환원하지 않는다.",
    },
  },
  {
    caseId: "golden_05_mixed_ops_growth_service",
    expectedCareerProfile: {
      totalExperienceMonths: 53,
      directlyRelevantMonths: 36,
      adjacentRelevantMonths: 17,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 1,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "operations",
      secondaryRoleFamilies: ["growth_marketing", "service_planning", "content_strategy"],
      industryDomains: ["commerce", "platform", "content_service"],
      adjacentIndustryDomains: ["education_career"],
      strengthSignals: [
        "운영기획 매니저 경력에서 파트너 온보딩, 운영 정책, KPI 대시보드, CRM 캠페인 신호가 함께 존재한다",
        "콘텐츠 마케팅 경력에서 랜딩 문구, 캠페인 리포트, 사용자 인터뷰, A/B 테스트 신호가 있다",
        "operations가 primary이고 growth_marketing, service_planning, content_strategy가 secondary로 분리된다",
      ],
      riskSignals: [
        "운영, 그로스, 콘텐츠, 서비스기획 신호가 혼합되어 있어 방향성 설명이 필요하다",
        "service_planning은 운영 데이터 기반 개선 과제로 드러나며 독립 primary로 보기는 이르다",
      ],
      evidenceAnchors: [
        "최유진 / 로컬커머스랩 / 운영기획 매니저 / 2021.06 ~ 2024.05",
        "파트너 온보딩, 운영 정책, KPI 대시보드, CRM 캠페인 운영안",
        "월 반복 주문율을 19% 높임",
        "브랜드콘텐츠랩 / 콘텐츠 마케팅 담당자 / 2019.12 ~ 2021.04",
      ],
      confidence: "high",
      rationale:
        "최유진은 commerce/platform operations가 중심이고 growth_marketing, service_planning, content_strategy 신호가 보조축으로 붙은 복합 경력자다. 하나의 모호한 운영 경력으로 뭉개지 않는 것이 기준선이다.",
    },
  },
]);
