import { DATE_FORMAT_TEST_REFERENCE_DATE } from "./dateFormatMatrix.js";

export const expectedDateParseResults = Object.freeze({
  date_01_dot_full_year: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_02_slash_full_year: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_03_dash_full_year: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_04_dot_single_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_05_inclusive_24_month_anchor: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-06",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 24,
    parseWarnings: [],
  },
  date_06_short_dot_year: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_07_short_slash_year: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_08_short_korean_single_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_09_short_korean_padded_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_10_korean_year_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_11_korean_from_to: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_12_korean_hire_leave: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_13_no_space_hyphen: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_14_en_dash: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_15_em_dash: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_16_tilde: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  date_17_wave_dash: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 25,
    parseWarnings: [],
  },
  present_01_korean_current: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_02_korean_employed_compact: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_03_korean_employed_spaced: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_04_english_present: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_05_english_now: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_06_korean_current_employed: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_07_hire_to_current: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: [],
  },
  present_08_open_ended: {
    normalizedStart: "2021-07",
    normalizedEnd: "2026-06",
    isCurrent: true,
    datePrecision: "month",
    durationMonthsInclusive: 60,
    testReferenceDate: DATE_FORMAT_TEST_REFERENCE_DATE,
    parseWarnings: ["open_ended_current_assumed"],
  },
  date_year_only_01_plain_tilde: {
    normalizedStart: "2021",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "year",
    durationMonthsRange: { min: 13, max: 36 },
    parseWarnings: ["month_missing"],
  },
  date_year_only_02_korean: {
    normalizedStart: "2021",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "year",
    durationMonthsRange: { min: 13, max: 36 },
    parseWarnings: ["month_missing"],
  },
  date_year_only_03_hyphen: {
    normalizedStart: "2021",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "year",
    durationMonthsRange: { min: 13, max: 36 },
    parseWarnings: ["month_missing"],
  },
  date_year_only_04_hire_leave: {
    normalizedStart: "2021",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "year",
    durationMonthsRange: { min: 13, max: 36 },
    parseWarnings: ["month_missing"],
  },
  date_partial_01_missing_end_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "partial_month",
    durationMonthsRange: { min: 19, max: 30 },
    parseWarnings: ["end_month_missing"],
  },
  date_partial_02_missing_start_month: {
    normalizedStart: "2021",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "partial_month",
    durationMonthsRange: { min: 20, max: 31 },
    parseWarnings: ["start_month_missing"],
  },
  date_partial_03_korean_missing_end_month: {
    normalizedStart: "2021-07",
    normalizedEnd: "2023",
    isCurrent: false,
    datePrecision: "partial_month",
    durationMonthsRange: { min: 19, max: 30 },
    parseWarnings: ["end_month_missing"],
  },
  date_partial_04_korean_missing_start_month: {
    normalizedStart: "2021",
    normalizedEnd: "2023-07",
    isCurrent: false,
    datePrecision: "partial_month",
    durationMonthsRange: { min: 20, max: 31 },
    parseWarnings: ["start_month_missing"],
  },
  gap_01_explicit_gap: {
    normalizedStart: "2019-08",
    normalizedEnd: "2023-09",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 50,
    timelineKind: "gap",
    parseWarnings: [],
  },
  gap_02_career_exploration_partial: {
    normalizedStart: "2019-H2",
    normalizedEnd: "2023-09",
    isCurrent: false,
    datePrecision: "partial_month",
    durationMonthsRange: { min: 46, max: 51 },
    timelineKind: "gap",
    parseWarnings: ["start_month_imprecise"],
  },
  gap_03_personal_reason: {
    normalizedStart: "2019-08",
    normalizedEnd: "2023-09",
    isCurrent: false,
    datePrecision: "month",
    durationMonthsInclusive: 50,
    timelineKind: "gap",
    parseWarnings: [],
  },
});
