export const expectedCareerProfiles = Object.freeze([
  {
    caseId: "golden_01_direct_service_planner",
    expectedCareerProfile: {
      totalExperienceMonths: 62,
      directlyRelevantMonths: 62,
      adjacentRelevantMonths: 0,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 0,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "service_planning_pm_po",
      secondaryRoleFamilies: ["product_operations", "customer_journey_design"],
      industryDomains: ["b2b_saas", "career_platform", "career_education"],
      adjacentIndustryDomains: ["hr_tech", "education_service"],
      strengthSignals: [
        "service planning and PM/PO execution are consistently present",
        "B2B SaaS career platform context is explicit",
        "quantified activation and workflow improvement evidence is present",
      ],
      riskSignals: [
        "scope may still be junior-to-mid depending on ownership depth",
      ],
      evidenceAnchors: [
        "Owned onboarding flow, requirements, backlog grooming, and release QA",
        "Improved paid activation from 18% to 31%",
        "Reduced manual counselor assignment work by 22%",
      ],
      confidence: "high",
      rationale:
        "This profile is a direct service planning/PM career with sustained career-platform and B2B SaaS exposure. Quantified outcome evidence should prevent weak-metric overclassification.",
    },
  },
  {
    caseId: "golden_02_career_consulting_to_service_planning",
    expectedCareerProfile: {
      totalExperienceMonths: 70,
      directlyRelevantMonths: 41,
      adjacentRelevantMonths: 29,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 1,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "career_consulting_operations",
      secondaryRoleFamilies: ["service_operations", "service_planning", "content_operations"],
      industryDomains: ["career_education", "employment_consulting", "hr_services"],
      adjacentIndustryDomains: ["hr_tech", "education_service", "content_media"],
      strengthSignals: [
        "career coaching operations include journey, triage, and matching-rule ownership",
        "service backlog translation and SOP redesign show planning transferability",
        "career education and employment consulting context is stable across roles",
      ],
      riskSignals: [
        "formal service planning title is not the dominant historical label",
        "product delivery ownership is inferred from operations artifacts, not explicit roadmap ownership",
      ],
      evidenceAnchors: [
        "Managed job transition coaching operations, counselor matching rules, intake triage",
        "Cut first consultation lead time from 4.2 days to 1.6 days",
        "Translated repeated coaching issues into service backlog items",
      ],
      confidence: "high",
      rationale:
        "This profile is a career consulting operations operator with strong service-planning transfer signals. It should not be reduced to customer support because the work includes process design, triage rules, and service backlog translation.",
    },
  },
  {
    caseId: "golden_03_manufacturing_quality_to_bio_operations",
    expectedCareerProfile: {
      totalExperienceMonths: 67,
      directlyRelevantMonths: 49,
      adjacentRelevantMonths: 18,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 1,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "production_quality_operations",
      secondaryRoleFamilies: ["quality_control", "process_operations", "risk_response"],
      industryDomains: ["manufacturing", "regulated_components"],
      adjacentIndustryDomains: ["bio_pharma_production", "medical_device", "quality_assurance"],
      strengthSignals: [
        "production quality record and nonconformance ownership is explicit",
        "regulated documentation and traceability appear across roles",
        "process deviation and corrective action signals support adjacent bio operations interpretation",
      ],
      riskSignals: [
        "bio-specific GMP exposure is adjacent rather than fully direct in the latest role",
        "inspection assistant history should be weighted lower than recent operations ownership",
      ],
      evidenceAnchors: [
        "Managed production quality records, nonconformance follow-up, and lot release documentation",
        "Reduced repeat inspection errors by 27%",
        "Escalated process deviation risks and coordinated corrective action",
      ],
      confidence: "high",
      rationale:
        "This profile is manufacturing production-quality operations with regulated process and risk-response evidence. Bio production and quality operations should be adjacent, not unrelated.",
    },
  },
  {
    caseId: "golden_04_gap_short_tenure_transition",
    expectedCareerProfile: {
      totalExperienceMonths: 29,
      directlyRelevantMonths: 17,
      adjacentRelevantMonths: 12,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 50,
      shortTenureCount: 1,
      recentExperienceWeight: "medium",
      primaryRoleFamily: "bio_production_operations",
      secondaryRoleFamilies: ["career_research", "evidence_classification", "operations_research"],
      industryDomains: ["bio_pharma_production", "career_research"],
      adjacentIndustryDomains: ["healthcare_pharma_bio", "employment_consulting", "hr_services"],
      strengthSignals: [
        "biopharma production, GMP records, and deviation reporting are explicit",
        "recent research assistant role adds evidence classification and labor-market analysis signals",
        "the profile contains both technical operations and analytical transition evidence",
      ],
      riskSignals: [
        "long career gap requires separate visibility",
        "recent transition role is short and should not erase earlier biopharma experience",
        "career direction is mixed between production operations and research support",
      ],
      evidenceAnchors: [
        "Biopharma Production Engineer from 2019-09 to 2021-01",
        "Career Research Assistant from 2025-04 to 2026-03",
        "Built spreadsheets for industry, role, and evidence pattern tagging across 180 candidate cases",
      ],
      confidence: "medium",
      rationale:
        "This profile has a real gap and short recent tenure, but it also has coherent biopharma operations history and recent analytical transition evidence. The gap is a risk signal, not a complete profile definition.",
    },
  },
  {
    caseId: "golden_05_mixed_ops_growth_service",
    expectedCareerProfile: {
      totalExperienceMonths: 53,
      directlyRelevantMonths: 33,
      adjacentRelevantMonths: 20,
      transferableMonths: 0,
      unrelatedMonths: 0,
      gapMonths: 0,
      shortTenureCount: 0,
      recentExperienceWeight: "high",
      primaryRoleFamily: "operations_planning",
      secondaryRoleFamilies: ["growth_marketing", "service_planning", "data_analysis"],
      industryDomains: ["commerce_platform", "growth_service", "content_marketing"],
      adjacentIndustryDomains: ["b2c_platform", "crm_marketing", "online_commerce"],
      strengthSignals: [
        "operations planning is the most recent and longest role family",
        "growth, CRM, dashboard, and funnel signals are explicitly present",
        "service policy and workflow experiments provide service-planning adjacency",
      ],
      riskSignals: [
        "mixed operations and marketing history may need direction clarification",
        "service planning should be secondary unless roadmap or product ownership becomes explicit",
      ],
      evidenceAnchors: [
        "Planned partner onboarding operations, KPI dashboards, workflow experiments",
        "Raised repeat partner activation by 19%",
        "Improved trial signup conversion by 14%",
      ],
      confidence: "high",
      rationale:
        "This profile is primarily operations planning with growth, content, data, and service-planning adjacency. The baseline should preserve distinct secondary families instead of collapsing the career into one generic operations label.",
    },
  },
]);
