export const careerCoreMutationIdeas = Object.freeze([
  {
    mutationId: "mutation_01_01_remove_metric_values",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "evidence_strength_reduction",
    changeSummary: "Remove numeric activation and workflow improvement values while keeping the same planning responsibilities.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "directlyRelevantMonths"],
    expectedChangedFields: ["strengthSignals", "riskSignals", "confidence"],
    purpose: "Check that role and industry identity remain stable even when metric strength weakens.",
  },
  {
    mutationId: "mutation_01_02_title_pm_to_service_planner",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "role_title_alias",
    changeSummary: "Change PM/PO-like title wording to service planner while preserving roadmap, backlog, and release ownership.",
    expectedStableFields: ["primaryRoleFamily", "secondaryRoleFamilies", "directlyRelevantMonths"],
    expectedChangedFields: ["evidenceAnchors"],
    purpose: "Prevent overdependence on a single PM/PO title string.",
  },
  {
    mutationId: "mutation_01_03_drop_b2b_phrase",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "industry_signal_partial_removal",
    changeSummary: "Remove the explicit B2B phrase from one bullet but keep enterprise HR team and SaaS platform context.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths"],
    expectedChangedFields: ["industryDomains", "confidence"],
    purpose: "Check whether industry detection uses multiple evidence anchors instead of one phrase.",
  },
  {
    mutationId: "mutation_02_01_counseling_wording_variation",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "responsibility_wording_variation",
    changeSummary: "Replace coaching and counseling wording with transition advisory operations and candidate journey wording.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "adjacentRelevantMonths"],
    expectedChangedFields: ["evidenceAnchors"],
    purpose: "Check that career consulting is not recognized only through counseling keywords.",
  },
  {
    mutationId: "mutation_02_02_remove_service_backlog_bullet",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "planning_signal_reduction",
    changeSummary: "Remove the service backlog bullet while keeping SOP redesign, triage, and matching-rule ownership.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains"],
    expectedChangedFields: ["secondaryRoleFamilies", "riskSignals", "confidence"],
    purpose: "Check that service-planning transferability weakens without erasing the career operations identity.",
  },
  {
    mutationId: "mutation_02_03_content_ops_metrics_removed",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "metric_signal_reduction",
    changeSummary: "Remove content performance metrics while preserving newsletter, webinar, and survey operations.",
    expectedStableFields: ["totalExperienceMonths", "primaryRoleFamily", "industryDomains"],
    expectedChangedFields: ["strengthSignals", "confidence"],
    purpose: "Check that content operations remains adjacent even when quantitative evidence is weaker.",
  },
  {
    mutationId: "mutation_03_01_remove_regulated_component_phrase",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "industry_signal_partial_removal",
    changeSummary: "Remove regulated component wording while retaining quality records, nonconformance, and lot release documentation.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths"],
    expectedChangedFields: ["industryDomains", "adjacentIndustryDomains", "confidence"],
    purpose: "Check whether regulated operations are inferred from process evidence rather than one industry phrase.",
  },
  {
    mutationId: "mutation_03_02_assistant_role_more_generic",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "early_role_specificity_reduction",
    changeSummary: "Make the quality inspection assistant bullets more generic while keeping recent production quality operations unchanged.",
    expectedStableFields: ["primaryRoleFamily", "recentExperienceWeight", "directlyRelevantMonths"],
    expectedChangedFields: ["adjacentRelevantMonths", "riskSignals"],
    purpose: "Check that recent operations ownership remains dominant over weaker early-role evidence.",
  },
  {
    mutationId: "mutation_03_03_change_quality_to_production_control",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "role_family_boundary",
    changeSummary: "Emphasize production control and process scheduling over inspection while preserving corrective-action evidence.",
    expectedStableFields: ["industryDomains", "adjacentIndustryDomains"],
    expectedChangedFields: ["primaryRoleFamily", "secondaryRoleFamilies"],
    purpose: "Check boundary behavior between production management and quality operations.",
  },
  {
    mutationId: "mutation_04_01_gap_shortened",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "timeline_gap_variation",
    changeSummary: "Shorten the gap by moving the research assistant start date earlier while preserving both roles.",
    expectedStableFields: ["primaryRoleFamily", "secondaryRoleFamilies", "industryDomains"],
    expectedChangedFields: ["gapMonths", "riskSignals", "recentExperienceWeight"],
    purpose: "Check that gap risk changes independently from role-family interpretation.",
  },
  {
    mutationId: "mutation_04_02_recent_role_extended",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "short_tenure_variation",
    changeSummary: "Extend the research assistant role beyond 18 months while keeping the earlier biopharma role unchanged.",
    expectedStableFields: ["industryDomains", "adjacentIndustryDomains"],
    expectedChangedFields: ["shortTenureCount", "recentExperienceWeight", "primaryRoleFamily"],
    purpose: "Check that recent transition weight changes without treating the gap as the whole profile.",
  },
  {
    mutationId: "mutation_04_03_remove_metric_case_count",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "research_evidence_reduction",
    changeSummary: "Remove the 180-case count from the research assistant bullet while preserving classification work.",
    expectedStableFields: ["gapMonths", "shortTenureCount", "secondaryRoleFamilies"],
    expectedChangedFields: ["strengthSignals", "confidence"],
    purpose: "Check that recent analytical transition evidence is still recognized with weaker metrics.",
  },
  {
    mutationId: "mutation_05_01_growth_terms_removed",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "secondary_role_signal_reduction",
    changeSummary: "Remove growth and funnel wording while keeping operations planning, CRM segmentation, and dashboard evidence.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths", "recentExperienceWeight"],
    expectedChangedFields: ["secondaryRoleFamilies", "strengthSignals"],
    purpose: "Check that operations planning remains primary while growth marketing signal strength changes.",
  },
  {
    mutationId: "mutation_05_02_content_role_more_product_like",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "secondary_role_boundary",
    changeSummary: "Add more user interview and landing experiment responsibility to the content role without changing dates.",
    expectedStableFields: ["totalExperienceMonths", "primaryRoleFamily", "industryDomains"],
    expectedChangedFields: ["secondaryRoleFamilies", "adjacentRelevantMonths"],
    purpose: "Check whether service-planning adjacency increases without overriding recent operations planning.",
  },
  {
    mutationId: "mutation_05_03_ops_role_less_quantified",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "metric_signal_reduction",
    changeSummary: "Remove activation percentage and trial conversion numbers while preserving operations and content responsibilities.",
    expectedStableFields: ["primaryRoleFamily", "secondaryRoleFamilies", "industryDomains"],
    expectedChangedFields: ["strengthSignals", "riskSignals", "confidence"],
    purpose: "Check that mixed-career direction is preserved while evidence strength becomes lower.",
  },
]);
