export const careerCoreMutationIdeas = Object.freeze([
  {
    mutationId: "mutation_01_01_metric_removed",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "metric_evidence_reduction",
    changeSummary: "김서윤 이력서에서 진단 완료율, 유료 상담 전환율, 월 32시간 절감 수치를 제거하고 서비스기획 책임은 유지한다.",
    expectedStableFields: ["primaryRoleFamily", "secondaryRoleFamilies", "industryDomains", "directlyRelevantMonths"],
    expectedChangedFields: ["strengthSignals", "riskSignals", "confidence"],
    purpose: "정량 성과가 약해져도 서비스기획/PM 및 커리어 플랫폼 경력 정체성이 유지되는지 확인한다.",
  },
  {
    mutationId: "mutation_01_02_pm_po_terms_removed",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "role_alias_boundary",
    changeSummary: "넥스트커리어랩 bullet에서 PO, PM 유사 표현을 제거하고 요구사항 정의, 화면 정책, 릴리즈 조율 표현만 남긴다.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths", "industryDomains"],
    expectedChangedFields: ["secondaryRoleFamilies", "evidenceAnchors"],
    purpose: "서비스기획과 product_planning_pm을 특정 영문 title에만 의존해 분리하지 않는지 확인한다.",
  },
  {
    mutationId: "mutation_01_03_career_platform_phrase_weakened",
    basedOn: "golden_01_direct_service_planner",
    mutationType: "industry_signal_reduction",
    changeSummary: "B2B SaaS와 커리어 플랫폼 표현을 약화하고 이력서 진단, 상담 예약, 기업 관리자 화면 맥락은 유지한다.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths"],
    expectedChangedFields: ["industryDomains", "adjacentIndustryDomains", "confidence"],
    purpose: "산업 해석이 단일 키워드가 아니라 여러 업무 anchor를 통해 유지되는지 확인한다.",
  },
  {
    mutationId: "mutation_02_01_coaching_to_advisory_wording",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "korean_wording_variation",
    changeSummary: "박민재 이력서의 이직코칭, 상담 표현을 커리어 전환 자문, 후보자 여정 운영 표현으로 바꾼다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "directlyRelevantMonths"],
    expectedChangedFields: ["evidenceAnchors"],
    purpose: "career_consulting 해석이 상담/코칭 단어 하나에만 의존하지 않는지 확인한다.",
  },
  {
    mutationId: "mutation_02_02_sop_redesign_removed",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "service_planning_signal_reduction",
    changeSummary: "첫 코칭 리드타임 개선과 SOP 재설계 bullet을 제거하고 매칭, 일정, 후속 과제 운영만 유지한다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "totalExperienceMonths"],
    expectedChangedFields: ["secondaryRoleFamilies", "strengthSignals", "confidence"],
    purpose: "service_planning 전환 신호가 약해져도 career_consulting operations 정체성은 유지되는지 확인한다.",
  },
  {
    mutationId: "mutation_02_03_content_operation_metrics_removed",
    basedOn: "golden_02_career_consulting_to_service_planning",
    mutationType: "content_strategy_evidence_reduction",
    changeSummary: "잡콘텐츠스튜디오 경력에서 신청 수, 참석률, 상담 전환율 추적 표현을 제거한다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "adjacentRelevantMonths"],
    expectedChangedFields: ["secondaryRoleFamilies", "strengthSignals"],
    purpose: "content_strategy 보조축이 약해져도 HR/커리어 교육 산업 맥락이 유지되는지 확인한다.",
  },
  {
    mutationId: "mutation_03_01_quality_terms_weakened",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "production_quality_signal_reduction",
    changeSummary: "이도현 이력서에서 불량, 검사, 품질 이슈 표현 일부를 줄이고 생산계획과 공정 실적 표현을 강화한다.",
    expectedStableFields: ["industryDomains", "directlyRelevantMonths", "recentExperienceWeight"],
    expectedChangedFields: ["primaryRoleFamily", "secondaryRoleFamilies"],
    purpose: "production_quality와 process_management 경계가 일반화 가능한 방식으로 움직이는지 확인한다.",
  },
  {
    mutationId: "mutation_03_02_bio_adjacent_phrase_added",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "adjacent_industry_signal_addition",
    changeSummary: "제조 품질 기록 bullet에 GMP 유사 문서관리, LOT 추적성 표현을 추가하되 바이오 직접 경력은 추가하지 않는다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "totalExperienceMonths"],
    expectedChangedFields: ["adjacentIndustryDomains", "confidence"],
    purpose: "bio_pharma가 직접 산업이 아니라 adjacentIndustryDomains로 강화되는지 확인한다.",
  },
  {
    mutationId: "mutation_03_03_quality_assistant_generic",
    basedOn: "golden_03_manufacturing_quality_to_bio_operations",
    mutationType: "early_role_specificity_reduction",
    changeSummary: "세영테크 품질검사 보조 경력을 단순 검사 지원으로 축약하고 한성정밀 생산관리 경력은 유지한다.",
    expectedStableFields: ["primaryRoleFamily", "recentExperienceWeight", "directlyRelevantMonths"],
    expectedChangedFields: ["adjacentRelevantMonths", "riskSignals"],
    purpose: "초기 보조 경력 약화가 최신 생산관리/품질 운영 정체성을 과도하게 흔들지 않는지 확인한다.",
  },
  {
    mutationId: "mutation_04_01_gap_shortened",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "timeline_gap_variation",
    changeSummary: "정하늘 이력서에서 커리어 리서치 어시스턴트 시작일을 앞당겨 약 50개월 공백을 단축한다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "secondaryRoleFamilies"],
    expectedChangedFields: ["gapMonths", "riskSignals", "recentExperienceWeight"],
    purpose: "공백 리스크가 role family 해석과 독립적으로 조정되는지 확인한다.",
  },
  {
    mutationId: "mutation_04_02_research_tenure_extended",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "short_tenure_variation",
    changeSummary: "커리어 리서치 어시스턴트 기간을 12개월에서 20개월 이상으로 늘리고 업무 내용은 유지한다.",
    expectedStableFields: ["industryDomains", "adjacentIndustryDomains"],
    expectedChangedFields: ["shortTenureCount", "recentExperienceWeight", "primaryRoleFamily"],
    purpose: "짧은 재직 리스크와 최근 전환 경험 weight가 분리되어 움직이는지 확인한다.",
  },
  {
    mutationId: "mutation_04_03_bio_production_detail_removed",
    basedOn: "golden_04_gap_short_tenure_transition",
    mutationType: "bio_production_signal_reduction",
    changeSummary: "삼성바이오로직스 경력에서 GMP 배치 기록, 공정 이상 보고 표현을 제거하고 설비 운전만 남긴다.",
    expectedStableFields: ["gapMonths", "shortTenureCount"],
    expectedChangedFields: ["primaryRoleFamily", "strengthSignals", "confidence"],
    purpose: "bio_pharma 경험의 구체성이 약해질 때 생산/품질 정체성과 리스크 표현이 조정되는지 확인한다.",
  },
  {
    mutationId: "mutation_05_01_growth_marketing_terms_removed",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "secondary_role_signal_reduction",
    changeSummary: "최유진 이력서에서 CRM 캠페인, A/B 테스트, 타깃 세그먼트 분석 표현을 제거하고 운영기획 표현은 유지한다.",
    expectedStableFields: ["primaryRoleFamily", "industryDomains", "directlyRelevantMonths"],
    expectedChangedFields: ["secondaryRoleFamilies", "strengthSignals"],
    purpose: "growth_marketing 보조축이 약해져도 operations primary가 유지되는지 확인한다.",
  },
  {
    mutationId: "mutation_05_02_service_planning_signal_added",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "service_planning_signal_addition",
    changeSummary: "로컬커머스랩 경력에 사용자 인터뷰 기반 기능 개선안, 화면 정책 정리 표현을 추가한다.",
    expectedStableFields: ["totalExperienceMonths", "industryDomains", "recentExperienceWeight"],
    expectedChangedFields: ["primaryRoleFamily", "secondaryRoleFamilies", "adjacentRelevantMonths"],
    purpose: "service_planning 신호가 강화될 때 operations와의 primary/secondary 구분이 어떻게 바뀌는지 확인한다.",
  },
  {
    mutationId: "mutation_05_03_content_service_context_weakened",
    basedOn: "golden_05_mixed_ops_growth_service",
    mutationType: "industry_signal_reduction",
    changeSummary: "브랜드콘텐츠랩 경력에서 콘텐츠 서비스 맥락을 약화하고 일반 마케팅 실행 표현으로 바꾼다.",
    expectedStableFields: ["primaryRoleFamily", "directlyRelevantMonths"],
    expectedChangedFields: ["industryDomains", "secondaryRoleFamilies", "confidence"],
    purpose: "content_service 산업 신호가 약해져도 commerce/platform operations 정체성이 유지되는지 확인한다.",
  },
]);
